export type SampleCategory = 'kick' | 'snare' | 'hihat' | 'perc' | 'clap' | 'cymbal' | 'tom';

export interface SampleDefinition {
    id: string; // The filename e.g. distkit-kick.wav
    label: string; // The display name e.g. "DistKit"
    category: SampleCategory;
    url: string; // The public path
}

export const DRUM_SAMPLES: Record<SampleCategory, SampleDefinition[]> = {
    kick: [
        { id: 'distkit-kick.wav', label: 'DistKit', category: 'kick', url: '/samples/distkit-kick.wav' },
        { id: 'sdbkit-kick.wav', label: 'SDBKit', category: 'kick', url: '/samples/sdbkit-kick.wav' },
        { id: 'sdbkit-sub-a.wav', label: 'SDBKit Sub', category: 'kick', url: '/samples/sdbkit-sub-a.wav' },
        { id: 'synthkit-kick.wav', label: 'SynthKit', category: 'kick', url: '/samples/synthkit-kick.wav' },
        { id: 'x0xproc1-kick.wav', label: 'X0x1', category: 'kick', url: '/samples/x0xproc1-kick.wav' },
        { id: 'x0xproc2-kick.wav', label: 'X0x2', category: 'kick', url: '/samples/x0xproc2-kick.wav' },
            { id: 'nd_808_-_ain_t_doin_that_c_.wav', label: "808 - Ain_t Doin Tha", category: 'kick', url: '/samples/new-drums/kick/808_-_ain_t_doin_that_c_.wav' },
        { id: 'nd_808_-_armed_and_dangerous_d_.wav', label: "808 - Armed And Dang", category: 'kick', url: '/samples/new-drums/kick/808_-_armed_and_dangerous_d_.wav' },
        { id: 'nd_808_-_bidness_d_.wav', label: "808 - Bidness [ D# ]", category: 'kick', url: '/samples/new-drums/kick/808_-_bidness_d_.wav' },
        { id: 'nd_808_-_harder_c_.wav', label: "808 - Harder [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_harder_c_.wav' },
        { id: 'nd_808_-_light_e_.wav', label: "808 - Light  [ E ]", category: 'kick', url: '/samples/new-drums/kick/808_-_light_e_.wav' },
        { id: 'nd_808_-_mind_e_.wav', label: "808 - Mind [ E ]", category: 'kick', url: '/samples/new-drums/kick/808_-_mind_e_.wav' },
        { id: 'nd_808_-_spinz_steroids_c_.wav', label: "808 - Spinz Steroids", category: 'kick', url: '/samples/new-drums/kick/808_-_spinz_steroids_c_.wav' },
        { id: 'nd_808_-_spinz_c_.wav', label: "808 - Spinz [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_spinz_c_.wav' },
        { id: 'nd_808_ardist_polarity_c_.wav', label: "808 ” Ardist Polarit", category: 'kick', url: '/samples/new-drums/kick/808_ardist_polarity_c_.wav' },
        { id: 'nd_808_the_only_recycled_drum_c_.wav', label: "808 ” the only recyc", category: 'kick', url: '/samples/new-drums/kick/808_the_only_recycled_drum_c_.wav' },
        { id: 'nd__ardist_808s_-_other_world_c_.wav', label: "[ARDIST] 808s - Othe", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_other_world_c_.wav' },
        { id: 'nd__ardist_808s_-_smokestack_c_.wav', label: "[ARDIST] 808s - Smok", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_smokestack_c_.wav' },
        { id: 'nd_808_-_baby_girl_d_.wav', label: "808 - Baby Girl [ D#", category: 'kick', url: '/samples/new-drums/kick/808_-_baby_girl_d_.wav' },
        { id: 'nd_808_-_bounce_out_c_.wav', label: "808 - Bounce Out [ C", category: 'kick', url: '/samples/new-drums/kick/808_-_bounce_out_c_.wav' },
        { id: 'nd_808_-_dear_momma_c_.wav', label: "808 - Dear Momma [ C", category: 'kick', url: '/samples/new-drums/kick/808_-_dear_momma_c_.wav' },
        { id: 'nd_808_-_early_20_rager_c_.wav', label: "808 - Early 20 Rager", category: 'kick', url: '/samples/new-drums/kick/808_-_early_20_rager_c_.wav' },
        { id: 'nd_808_-_pi_erre_c_.wav', label: "808 - Pi_erre [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_pi_erre_c_.wav' },
        { id: 'nd_808_-_wasted_c_.wav', label: "808 - Wasted [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_wasted_c_.wav' },
        { id: 'nd_808_-_yawn_d_.wav', label: "808 - Yawn [ D# ]", category: 'kick', url: '/samples/new-drums/kick/808_-_yawn_d_.wav' },
        { id: 'nd_808_-_zay_spinz_c_.wav', label: "808 - Zay Spinz [ C ", category: 'kick', url: '/samples/new-drums/kick/808_-_zay_spinz_c_.wav' },
        { id: 'nd__jynx_808s_-_wow_kenny_b_.wav', label: "[JYNX] 808s - wow!ke", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_wow_kenny_b_.wav' },
        { id: 'nd_808_-_321_c_.wav', label: "808 - 321 [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_321_c_.wav' },
        { id: 'nd_808_-_antidote_b_.wav', label: "808 - Antidote [ B ]", category: 'kick', url: '/samples/new-drums/kick/808_-_antidote_b_.wav' },
        { id: 'nd_808_-_antidote_c_.wav', label: "808 - Antidote [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_antidote_c_.wav' },
        { id: 'nd_808_-_giggz_g_.wav', label: "808 - Giggz [ G ]", category: 'kick', url: '/samples/new-drums/kick/808_-_giggz_g_.wav' },
        { id: 'nd_808_-_heartbreak_c_.wav', label: "808 - Heartbreak [ C", category: 'kick', url: '/samples/new-drums/kick/808_-_heartbreak_c_.wav' },
        { id: 'nd_808_-_la_uzi_c_.wav', label: "808 - La Uzi [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_la_uzi_c_.wav' },
        { id: 'nd_808_-_lean_c_.wav', label: "808 - Lean [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_lean_c_.wav' },
        { id: 'nd_808_-_lucid_d_.wav', label: "808 - Lucid [ D ]", category: 'kick', url: '/samples/new-drums/kick/808_-_lucid_d_.wav' },
        { id: 'nd_808_-_mirror_c_.wav', label: "808 - Mirror [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_mirror_c_.wav' },
        { id: 'nd_808_-_moonlight_f_.wav', label: "808 - Moonlight [ F ", category: 'kick', url: '/samples/new-drums/kick/808_-_moonlight_f_.wav' },
        { id: 'nd_808_-_murda_c_.wav', label: "808 - Murda [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_murda_c_.wav' },
        { id: 'nd_808_-_red_light_g_.wav', label: "808 - Red Light [ G ", category: 'kick', url: '/samples/new-drums/kick/808_-_red_light_g_.wav' },
        { id: 'nd_808_-_simple_c_.wav', label: "808 - Simple [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_simple_c_.wav' },
        { id: 'nd_808_-_zpins_c_.wav', label: "808 - Zpins [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_zpins_c_.wav' },
        { id: 'nd_808_i_thought_about_murder_a_.wav', label: "808 ” i thought abou", category: 'kick', url: '/samples/new-drums/kick/808_i_thought_about_murder_a_.wav' },
        { id: 'nd_808_oh_hell_yea_c_.wav', label: "808 ” oh hell yea ” ", category: 'kick', url: '/samples/new-drums/kick/808_oh_hell_yea_c_.wav' },
        { id: 'nd_808_on_the_radio_stereo_c_.wav', label: "808 ” on the radio, ", category: 'kick', url: '/samples/new-drums/kick/808_on_the_radio_stereo_c_.wav' },
        { id: 'nd_808_red_room_c_.wav', label: "808 ” red room ” [ C", category: 'kick', url: '/samples/new-drums/kick/808_red_room_c_.wav' },
        { id: 'nd_808_this_aint_that_c_.wav', label: "808 ” this aint that", category: 'kick', url: '/samples/new-drums/kick/808_this_aint_that_c_.wav' },
        { id: 'nd__ardist_808_-_fake_love_c_.wav', label: "[ARDIST] 808 - Fake ", category: 'kick', url: '/samples/new-drums/kick/_ardist_808_-_fake_love_c_.wav' },
        { id: 'nd__ardist_808_-_van_c_.wav', label: "[ARDIST] 808 - Van [", category: 'kick', url: '/samples/new-drums/kick/_ardist_808_-_van_c_.wav' },
        { id: 'nd__ardist_808s_-_mitch_d_.wav', label: "[ARDIST] 808s - Mitc", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_mitch_d_.wav' },
        { id: 'nd__blvnts_808_-_drift_c_.wav', label: "[BLVNTS] 808 - Drift", category: 'kick', url: '/samples/new-drums/kick/_blvnts_808_-_drift_c_.wav' },
        { id: 'nd__blvnts_808_-_reaper_c_.wav', label: "[BLVNTS] 808 - Reape", category: 'kick', url: '/samples/new-drums/kick/_blvnts_808_-_reaper_c_.wav' },
        { id: 'nd__jynx_808s_-_hotbox_f_.wav', label: "[JYNX] 808s - Hotbox", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_hotbox_f_.wav' },
        { id: 'nd_808_-_agats_c_.wav', label: "808 - AGATS [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_agats_c_.wav' },
        { id: 'nd_808_-_big_face_c_.wav', label: "808 - Big Face [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_big_face_c_.wav' },
        { id: 'nd_808_-_cc_c_.wav', label: "808 - CC [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_cc_c_.wav' },
        { id: 'nd_808_-_fruit_kick_c_.wav', label: "808 - Fruit Kick [ C", category: 'kick', url: '/samples/new-drums/kick/808_-_fruit_kick_c_.wav' },
        { id: 'nd_808_-_loom_c_.wav', label: "808 - Loom [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_loom_c_.wav' },
        { id: 'nd_808_-_red_card_c_.wav', label: "808 - Red Card [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_red_card_c_.wav' },
        { id: 'nd_808_second_off_c_.wav', label: "808 ” SECOND OFF ” [", category: 'kick', url: '/samples/new-drums/kick/808_second_off_c_.wav' },
        { id: 'nd__ardist_808s_-_preme_c_.wav', label: "[ARDIST] 808s - Prem", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_preme_c_.wav' },
        { id: 'nd__jynx_808s_-_plur_c_.wav', label: "[JYNX] 808s - plur [", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_plur_c_.wav' },
        { id: 'nd__jynx_808s_-_sluglord_b_.wav', label: "[JYNX] 808s - sluglo", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_sluglord_b_.wav' },
        { id: 'nd_808_-_123_c_.wav', label: "808 - 123 [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_123_c_.wav' },
        { id: 'nd_808_-_20_min_c_.wav', label: "808 - 20 Min [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_20_min_c_.wav' },
        { id: 'nd_808_-_444_222_g_.wav', label: "808 - 444+222 [ G ]", category: 'kick', url: '/samples/new-drums/kick/808_-_444_222_g_.wav' },
        { id: 'nd_808_-_bic_d_.wav', label: "808 - Bic [ D# ]", category: 'kick', url: '/samples/new-drums/kick/808_-_bic_d_.wav' },
        { id: 'nd_808_-_bored_c_.wav', label: "808 - Bored [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_bored_c_.wav' },
        { id: 'nd_808_-_curve_c_.wav', label: "808 - Curve [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_curve_c_.wav' },
        { id: 'nd_808_-_killshot_c_.wav', label: "808 - Killshot [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_killshot_c_.wav' },
        { id: 'nd_808_-_lean_wit_me_c_.wav', label: "808 - Lean Wit Me [ ", category: 'kick', url: '/samples/new-drums/kick/808_-_lean_wit_me_c_.wav' },
        { id: 'nd_808_-_lucid_dreams_c_.wav', label: "808 - Lucid Dreams [", category: 'kick', url: '/samples/new-drums/kick/808_-_lucid_dreams_c_.wav' },
        { id: 'nd_808_-_moonlight_c_.wav', label: "808 - Moonlight [ C ", category: 'kick', url: '/samples/new-drums/kick/808_-_moonlight_c_.wav' },
        { id: 'nd_808_-_nameless_e_.wav', label: "808 - Nameless [ E ]", category: 'kick', url: '/samples/new-drums/kick/808_-_nameless_e_.wav' },
        { id: 'nd_808_-_no_heart_c_.wav', label: "808 - No Heart [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_no_heart_c_.wav' },
        { id: 'nd_808_-_props_c_.wav', label: "808 - Props [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_props_c_.wav' },
        { id: 'nd_808_-_r.i.p._c_.wav', label: "808 - R.I.P. [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_r.i.p._c_.wav' },
        { id: 'nd_808_iann_dior_c_.wav', label: "808 ” iann dior ” [ ", category: 'kick', url: '/samples/new-drums/kick/808_iann_dior_c_.wav' },
        { id: 'nd__ardist_808_-_look_away_c_.wav', label: "[ARDIST] 808 - Look ", category: 'kick', url: '/samples/new-drums/kick/_ardist_808_-_look_away_c_.wav' },
        { id: 'nd__ardist_808s_-_pelvic_e_.wav', label: "[ARDIST] 808s - Pelv", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_pelvic_e_.wav' },
        { id: 'nd__blvnts_808_-_guilty_c_.wav', label: "[BLVNTS] 808 - Guilt", category: 'kick', url: '/samples/new-drums/kick/_blvnts_808_-_guilty_c_.wav' },
        { id: 'nd__jynx_808s_-_mira.cle_c_.wav', label: "[JYNX] 808s - mira.c", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_mira.cle_c_.wav' },
        { id: 'nd_808_-_baby_c_.wav', label: "808 - Baby [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_baby_c_.wav' },
        { id: 'nd_808_-_going_dummi_c_.wav', label: "808 - Going Dummi [ ", category: 'kick', url: '/samples/new-drums/kick/808_-_going_dummi_c_.wav' },
        { id: 'nd_808_-_jeffery_c_.wav', label: "808 - Jeffery [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_jeffery_c_.wav' },
        { id: 'nd_808_-_maserati_e_.wav', label: "808 - Maserati [ E ]", category: 'kick', url: '/samples/new-drums/kick/808_-_maserati_e_.wav' },
        { id: 'nd_808_-_testing_c_.wav', label: "808 - Testing [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_-_testing_c_.wav' },
        { id: 'nd_808_-_wonder_wrld_c_.wav', label: "808 - Wonder WRLD [ ", category: 'kick', url: '/samples/new-drums/kick/808_-_wonder_wrld_c_.wav' },
        { id: 'nd_808_bigums_c_.wav', label: "808 ” bigums ” [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_bigums_c_.wav' },
        { id: 'nd_808_buy_van_beats_edit_c_.wav', label: "808 ” buy van beats ", category: 'kick', url: '/samples/new-drums/kick/808_buy_van_beats_edit_c_.wav' },
        { id: 'nd_808_buy_van_beats_c_.wav', label: "808 ” buy van beats ", category: 'kick', url: '/samples/new-drums/kick/808_buy_van_beats_c_.wav' },
        { id: 'nd_808_dropout_b_.wav', label: "808 ” dropout ” [ B ", category: 'kick', url: '/samples/new-drums/kick/808_dropout_b_.wav' },
        { id: 'nd_808_jah_c_.wav', label: "808 ” jah ” [ C ]", category: 'kick', url: '/samples/new-drums/kick/808_jah_c_.wav' },
        { id: 'nd_magnolia_e_.wav', label: "Magnolia [ E ]", category: 'kick', url: '/samples/new-drums/kick/magnolia_e_.wav' },
        { id: 'nd__ardist_808_-_i_won_t_c_.wav', label: "[ARDIST] 808 - I Won", category: 'kick', url: '/samples/new-drums/kick/_ardist_808_-_i_won_t_c_.wav' },
        { id: 'nd__ardist_808_-_shifty_c_.wav', label: "[ARDIST] 808 - Shift", category: 'kick', url: '/samples/new-drums/kick/_ardist_808_-_shifty_c_.wav' },
        { id: 'nd__ardist_808s_-_duppy_c_.wav', label: "[ARDIST] 808s - Dupp", category: 'kick', url: '/samples/new-drums/kick/_ardist_808s_-_duppy_c_.wav' },
        { id: 'nd__jynx_808s_-_sloppy_toppy_c_.wav', label: "[JYNX] 808s - sloppy", category: 'kick', url: '/samples/new-drums/kick/_jynx_808s_-_sloppy_toppy_c_.wav' },
        { id: 'nd_kick_-_123.wav', label: "Kick - 123", category: 'kick', url: '/samples/new-drums/kick/kick_-_123.wav' },
        { id: 'nd_kick_badder_.wav', label: "Kick [ Badder ]", category: 'kick', url: '/samples/new-drums/kick/kick_badder_.wav' },
        { id: 'nd_kick_big_.wav', label: "Kick [ Big ]", category: 'kick', url: '/samples/new-drums/kick/kick_big_.wav' },
        { id: 'nd_kick_e_.wav', label: "Kick [ E ]", category: 'kick', url: '/samples/new-drums/kick/kick_e_.wav' },
        { id: 'nd_kick_enough_.wav', label: "Kick [ Enough ]", category: 'kick', url: '/samples/new-drums/kick/kick_enough_.wav' },
        { id: 'nd_kick_grizzley_.wav', label: "Kick [ Grizzley ]", category: 'kick', url: '/samples/new-drums/kick/kick_grizzley_.wav' },
        { id: 'nd_kick_hidden_hills_.wav', label: "Kick [ Hidden Hills ", category: 'kick', url: '/samples/new-drums/kick/kick_hidden_hills_.wav' },
        { id: 'nd_kick_mortal_.wav', label: "Kick [ Mortal ]", category: 'kick', url: '/samples/new-drums/kick/kick_mortal_.wav' },
        { id: 'nd_kick_pacc_.wav', label: "Kick [ Pacc ]", category: 'kick', url: '/samples/new-drums/kick/kick_pacc_.wav' },
        { id: 'nd_kick_rack_.wav', label: "Kick [ Rack ]", category: 'kick', url: '/samples/new-drums/kick/kick_rack_.wav' },
        { id: 'nd_kick_savage_.wav', label: "Kick [ Savage ]", category: 'kick', url: '/samples/new-drums/kick/kick_savage_.wav' },
        { id: 'nd_kick_sicko_.wav', label: "Kick [ Sicko ]", category: 'kick', url: '/samples/new-drums/kick/kick_sicko_.wav' },
        { id: 'nd_kick_slime_.wav', label: "Kick [ Slime ]", category: 'kick', url: '/samples/new-drums/kick/kick_slime_.wav' },
        { id: 'nd_kick_smash_.wav', label: "Kick [ Smash ]", category: 'kick', url: '/samples/new-drums/kick/kick_smash_.wav' },
        { id: 'nd_kick_smoke_.wav', label: "Kick [ Smoke ]", category: 'kick', url: '/samples/new-drums/kick/kick_smoke_.wav' },
        { id: 'nd_kick_thank_u_.wav', label: "Kick [ Thank u ]", category: 'kick', url: '/samples/new-drums/kick/kick_thank_u_.wav' },
        { id: 'nd__ardist_kick_-_almnac.wav', label: "[ARDIST] Kick - Almn", category: 'kick', url: '/samples/new-drums/kick/_ardist_kick_-_almnac.wav' },
        { id: 'nd__ardist_kick_-_dios.wav', label: "[ARDIST] Kick - Dios", category: 'kick', url: '/samples/new-drums/kick/_ardist_kick_-_dios.wav' },
        { id: 'nd__ardist_kick_-_duppy.wav', label: "[ARDIST] Kick - Dupp", category: 'kick', url: '/samples/new-drums/kick/_ardist_kick_-_duppy.wav' },
        { id: 'nd__ardist_kick_-_secrets.wav', label: "[ARDIST] Kick - Secr", category: 'kick', url: '/samples/new-drums/kick/_ardist_kick_-_secrets.wav' },
        { id: 'nd__ardist_kicks_-_bodied.wav', label: "[ARDIST] Kicks - Bod", category: 'kick', url: '/samples/new-drums/kick/_ardist_kicks_-_bodied.wav' },
        { id: 'nd__ardist_kicks_-_derek.wav', label: "[ARDIST] Kicks - Der", category: 'kick', url: '/samples/new-drums/kick/_ardist_kicks_-_derek.wav' },
        { id: 'nd__ardist_kicks_-_dooma.wav', label: "[ARDIST] Kicks - Doo", category: 'kick', url: '/samples/new-drums/kick/_ardist_kicks_-_dooma.wav' },
        { id: 'nd__ardist_kicks_-_majin.wav', label: "[ARDIST] Kicks - Maj", category: 'kick', url: '/samples/new-drums/kick/_ardist_kicks_-_majin.wav' },
        { id: 'nd__ardist_kicks_-_van.wav', label: "[ARDIST] Kicks - Van", category: 'kick', url: '/samples/new-drums/kick/_ardist_kicks_-_van.wav' },
        { id: 'nd__blvnts_kick_-_dread.wav', label: "[BLVNTS] Kick - Drea", category: 'kick', url: '/samples/new-drums/kick/_blvnts_kick_-_dread.wav' },
        { id: 'nd__jynx_kicks_-_suppressed.wav', label: "[JYNX] Kicks - suppr", category: 'kick', url: '/samples/new-drums/kick/_jynx_kicks_-_suppressed.wav' },
        { id: 'nd__jynx_kicks_-_warehouse.wav', label: "[JYNX] Kicks - wareh", category: 'kick', url: '/samples/new-drums/kick/_jynx_kicks_-_warehouse.wav' },
        { id: 'nd_kick_astro_.wav', label: "Kick [ Astro ]", category: 'kick', url: '/samples/new-drums/kick/kick_astro_.wav' },
        { id: 'nd_kick_dior_.wav', label: "Kick [ Dior ]", category: 'kick', url: '/samples/new-drums/kick/kick_dior_.wav' },
        { id: 'nd_kick_glammor_.wav', label: "Kick [ Glammor ]", category: 'kick', url: '/samples/new-drums/kick/kick_glammor_.wav' },
        { id: 'nd_kick_hi_bridge_.wav', label: "Kick [ Hi Bridge ]", category: 'kick', url: '/samples/new-drums/kick/kick_hi_bridge_.wav' },
        { id: 'nd_kick_latitude_.wav', label: "Kick [ Latitude ]", category: 'kick', url: '/samples/new-drums/kick/kick_latitude_.wav' },
        { id: 'nd_kick_oomp_.wav', label: "Kick [ Oomp ]", category: 'kick', url: '/samples/new-drums/kick/kick_oomp_.wav' },
        { id: 'nd_kick_sick_.wav', label: "Kick [ Sick ]", category: 'kick', url: '/samples/new-drums/kick/kick_sick_.wav' },
        { id: 'nd_kick_vlone_.wav', label: "Kick [ VLONE ]", category: 'kick', url: '/samples/new-drums/kick/kick_vlone_.wav' },
        { id: 'nd_kick_wonder_wrld_.wav', label: "Kick [ Wonder WRLD ]", category: 'kick', url: '/samples/new-drums/kick/kick_wonder_wrld_.wav' },
        { id: 'nd__jynx_kicks_-_moody.wav', label: "[JYNX] Kicks - moody", category: 'kick', url: '/samples/new-drums/kick/_jynx_kicks_-_moody.wav' },
        { id: 'nd__jynx_kicks_-_safehouse.wav', label: "[JYNX] Kicks - safeh", category: 'kick', url: '/samples/new-drums/kick/_jynx_kicks_-_safehouse.wav' },
        { id: 'nd_kick_100_mill_.wav', label: "Kick [ 100 Mill ]", category: 'kick', url: '/samples/new-drums/kick/kick_100_mill_.wav' },
        { id: 'nd_kick_astronomical_.wav', label: "Kick [ Astronomical ", category: 'kick', url: '/samples/new-drums/kick/kick_astronomical_.wav' },
        { id: 'nd_kick_brick_.wav', label: "Kick [ Brick ]", category: 'kick', url: '/samples/new-drums/kick/kick_brick_.wav' },
        { id: 'nd_kick_extended_break_.wav', label: "Kick [ Extended Brea", category: 'kick', url: '/samples/new-drums/kick/kick_extended_break_.wav' },
        { id: 'nd_kick_ghz_.wav', label: "Kick [ Ghz ]", category: 'kick', url: '/samples/new-drums/kick/kick_ghz_.wav' },
        { id: 'nd_kick_humble_.wav', label: "Kick [ Humble ]", category: 'kick', url: '/samples/new-drums/kick/kick_humble_.wav' },
        { id: 'nd_kick_imperial_.wav', label: "Kick [ Imperial ]", category: 'kick', url: '/samples/new-drums/kick/kick_imperial_.wav' },
        { id: 'nd_kick_keeps_.wav', label: "Kick [ Keeps ]", category: 'kick', url: '/samples/new-drums/kick/kick_keeps_.wav' },
        { id: 'nd_kick_knite_.wav', label: "Kick [ Knite ]", category: 'kick', url: '/samples/new-drums/kick/kick_knite_.wav' },
        { id: 'nd_kick_pablo_.wav', label: "Kick [ Pablo ]", category: 'kick', url: '/samples/new-drums/kick/kick_pablo_.wav' },
        { id: 'nd_kick_perfect_.wav', label: "Kick [ Perfect ]", category: 'kick', url: '/samples/new-drums/kick/kick_perfect_.wav' },
        { id: 'nd__ardist_kick_-_crooked_ways.wav', label: "[ARDIST] Kick - Croo", category: 'kick', url: '/samples/new-drums/kick/_ardist_kick_-_crooked_ways.wav' },
        { id: 'nd__blvnts_kick_-_vvs.wav', label: "[BLVNTS] Kick - VVS", category: 'kick', url: '/samples/new-drums/kick/_blvnts_kick_-_vvs.wav' },
],
    snare: [
        { id: 'distkit-snare.wav', label: 'DistKit', category: 'snare', url: '/samples/distkit-snare.wav' },
        { id: 'sdbkit-snare.wav', label: 'SDBKit', category: 'snare', url: '/samples/sdbkit-snare.wav' },
        { id: 'synthkit-snare.wav', label: 'SynthKit', category: 'snare', url: '/samples/synthkit-snare.wav' },
        { id: 'x0xproc1-snare.wav', label: 'X0x1', category: 'snare', url: '/samples/x0xproc1-snare.wav' },
        { id: 'x0xproc2-snare.wav', label: 'X0x2', category: 'snare', url: '/samples/x0xproc2-snare.wav' },
            { id: 'nd_snare_-_90210.wav', label: "Snare - 90210", category: 'snare', url: '/samples/new-drums/snare/snare_-_90210.wav' },
        { id: 'nd_snare_-_itching.wav', label: "Snare - Itching", category: 'snare', url: '/samples/new-drums/snare/snare_-_itching.wav' },
        { id: 'nd_snare_-_xan.wav', label: "Snare - Xan", category: 'snare', url: '/samples/new-drums/snare/snare_-_xan.wav' },
        { id: 'nd_snare_bop_.wav', label: "Snare [ Bop ]", category: 'snare', url: '/samples/new-drums/snare/snare_bop_.wav' },
        { id: 'nd_snare_drako_.wav', label: "Snare [ Drako ]", category: 'snare', url: '/samples/new-drums/snare/snare_drako_.wav' },
        { id: 'nd_snare_factory_.wav', label: "Snare [ Factory ]", category: 'snare', url: '/samples/new-drums/snare/snare_factory_.wav' },
        { id: 'nd_snare_free_coke_.wav', label: "Snare [ Free Coke ]", category: 'snare', url: '/samples/new-drums/snare/snare_free_coke_.wav' },
        { id: 'nd_snare_gaze_.wav', label: "Snare [ Gaze ]", category: 'snare', url: '/samples/new-drums/snare/snare_gaze_.wav' },
        { id: 'nd_snare_recount_.wav', label: "Snare [ Recount ]", category: 'snare', url: '/samples/new-drums/snare/snare_recount_.wav' },
        { id: 'nd_snare_rock_.wav', label: "Snare [ Rock ]", category: 'snare', url: '/samples/new-drums/snare/snare_rock_.wav' },
        { id: 'nd_snare_scott_.wav', label: "Snare [ Scott ]", category: 'snare', url: '/samples/new-drums/snare/snare_scott_.wav' },
        { id: 'nd_snare_shiggy_.wav', label: "Snare [ Shiggy ]", category: 'snare', url: '/samples/new-drums/snare/snare_shiggy_.wav' },
        { id: 'nd__ardist_snare_-_30_30.wav', label: "[ARDIST] Snare - 30 ", category: 'snare', url: '/samples/new-drums/snare/_ardist_snare_-_30_30.wav' },
        { id: 'nd__ardist_snare_-_album_mode.wav', label: "[ARDIST] Snare - Alb", category: 'snare', url: '/samples/new-drums/snare/_ardist_snare_-_album_mode.wav' },
        { id: 'nd__ardist_snare_-_did_i_loose_you.wav', label: "[ARDIST] Snare - did", category: 'snare', url: '/samples/new-drums/snare/_ardist_snare_-_did_i_loose_you.wav' },
        { id: 'nd__ardist_snare_-_too_late.wav', label: "[ARDIST] Snare - Too", category: 'snare', url: '/samples/new-drums/snare/_ardist_snare_-_too_late.wav' },
        { id: 'nd__ardist_snares_-_shank.wav', label: "[ARDIST] Snares - Sh", category: 'snare', url: '/samples/new-drums/snare/_ardist_snares_-_shank.wav' },
        { id: 'nd__jynx_snares_-_ffffff.wav', label: "[JYNX] Snares - #fff", category: 'snare', url: '/samples/new-drums/snare/_jynx_snares_-_ffffff.wav' },
        { id: 'nd_snare_-_baby_girl.wav', label: "Snare - Baby Girl", category: 'snare', url: '/samples/new-drums/snare/snare_-_baby_girl.wav' },
        { id: 'nd_snare_aintchu_.wav', label: "Snare [ Aintchu ]", category: 'snare', url: '/samples/new-drums/snare/snare_aintchu_.wav' },
        { id: 'nd_snare_ball_player_.wav', label: "Snare [ Ball Player ", category: 'snare', url: '/samples/new-drums/snare/snare_ball_player_.wav' },
        { id: 'nd_snare_command_.wav', label: "Snare [ Command ]", category: 'snare', url: '/samples/new-drums/snare/snare_command_.wav' },
        { id: 'nd_snare_gramy_.wav', label: "Snare [ Gramy ]", category: 'snare', url: '/samples/new-drums/snare/snare_gramy_.wav' },
        { id: 'nd_snare_headless_.wav', label: "Snare [ Headless ]", category: 'snare', url: '/samples/new-drums/snare/snare_headless_.wav' },
        { id: 'nd_snare_jumpman_.wav', label: "Snare [ Jumpman ]", category: 'snare', url: '/samples/new-drums/snare/snare_jumpman_.wav' },
        { id: 'nd_snare_layer_down_.wav', label: "Snare [ Layer Down ]", category: 'snare', url: '/samples/new-drums/snare/snare_layer_down_.wav' },
        { id: 'nd_snare_layer_up_.wav', label: "Snare [ Layer Up ]", category: 'snare', url: '/samples/new-drums/snare/snare_layer_up_.wav' },
        { id: 'nd_snare_life_goes_.wav', label: "Snare [ Life Goes ]", category: 'snare', url: '/samples/new-drums/snare/snare_life_goes_.wav' },
        { id: 'nd_snare_metro_.wav', label: "Snare [ Metro ]", category: 'snare', url: '/samples/new-drums/snare/snare_metro_.wav' },
        { id: 'nd_snare_mood_.wav', label: "Snare [ Mood ]", category: 'snare', url: '/samples/new-drums/snare/snare_mood_.wav' },
        { id: 'nd_snare_rage_.wav', label: "Snare [ Rage ]", category: 'snare', url: '/samples/new-drums/snare/snare_rage_.wav' },
        { id: 'nd_snare_sad_future_.wav', label: "Snare [ Sad Future ]", category: 'snare', url: '/samples/new-drums/snare/snare_sad_future_.wav' },
        { id: 'nd_snare_scope_.wav', label: "Snare [ Scope ]", category: 'snare', url: '/samples/new-drums/snare/snare_scope_.wav' },
        { id: 'nd_snare_see_u_.wav', label: "Snare [ See U ]", category: 'snare', url: '/samples/new-drums/snare/snare_see_u_.wav' },
        { id: 'nd_snare_snake_.wav', label: "Snare [ Snake ]", category: 'snare', url: '/samples/new-drums/snare/snare_snake_.wav' },
        { id: 'nd_snare_uzi_.wav', label: "Snare [ Uzi ]", category: 'snare', url: '/samples/new-drums/snare/snare_uzi_.wav' },
        { id: 'nd_snare_wah_.wav', label: "Snare [ Wah ]", category: 'snare', url: '/samples/new-drums/snare/snare_wah_.wav' },
        { id: 'nd__snare_canadian_goose.wav', label: "[ Snare ] Canadian G", category: 'snare', url: '/samples/new-drums/snare/_snare_canadian_goose.wav' },
        { id: 'nd__snare_unfazed.wav', label: "[ Snare ] UnFazed", category: 'snare', url: '/samples/new-drums/snare/_snare_unfazed.wav' },
        { id: 'nd__ardist_snare_-_immunity.wav', label: "[ARDIST] Snare - Imm", category: 'snare', url: '/samples/new-drums/snare/_ardist_snare_-_immunity.wav' },
        { id: 'nd__ardist_snares_-_donut.wav', label: "[ARDIST] Snares - Do", category: 'snare', url: '/samples/new-drums/snare/_ardist_snares_-_donut.wav' },
        { id: 'nd__ardist_snares_-_work.wav', label: "[ARDIST] Snares - Wo", category: 'snare', url: '/samples/new-drums/snare/_ardist_snares_-_work.wav' },
        { id: 'nd__jynx_snares_-_cuisine.wav', label: "[JYNX] Snares - cuis", category: 'snare', url: '/samples/new-drums/snare/_jynx_snares_-_cuisine.wav' },
        { id: 'nd_snare_-_cheers.wav', label: "Snare - Cheers", category: 'snare', url: '/samples/new-drums/snare/snare_-_cheers.wav' },
        { id: 'nd_snare_-_everythang.wav', label: "Snare - Everythang", category: 'snare', url: '/samples/new-drums/snare/snare_-_everythang.wav' },
        { id: 'nd_snare_-_paak.wav', label: "Snare - Paak", category: 'snare', url: '/samples/new-drums/snare/snare_-_paak.wav' },
        { id: 'nd_snare_channel_.wav', label: "Snare [ Channel ]", category: 'snare', url: '/samples/new-drums/snare/snare_channel_.wav' },
        { id: 'nd_snare_flooded_.wav', label: "Snare [ Flooded ]", category: 'snare', url: '/samples/new-drums/snare/snare_flooded_.wav' },
        { id: 'nd_snare_kod_.wav', label: "Snare [ KOD ]", category: 'snare', url: '/samples/new-drums/snare/snare_kod_.wav' },
        { id: 'nd_snare_past_tense_.wav', label: "Snare [ Past Tense ]", category: 'snare', url: '/samples/new-drums/snare/snare_past_tense_.wav' },
        { id: 'nd_snare_pieces_.wav', label: "Snare [ Pieces ]", category: 'snare', url: '/samples/new-drums/snare/snare_pieces_.wav' },
        { id: 'nd_snare_scrape_.wav', label: "Snare [ Scrape ]", category: 'snare', url: '/samples/new-drums/snare/snare_scrape_.wav' },
        { id: 'nd_snare_anti_.wav', label: "Snare [ Anti ]", category: 'snare', url: '/samples/new-drums/snare/snare_anti_.wav' },
        { id: 'nd_snare_box_.wav', label: "Snare [ Box ]", category: 'snare', url: '/samples/new-drums/snare/snare_box_.wav' },
        { id: 'nd_snare_deebo_.wav', label: "Snare [ Deebo ]", category: 'snare', url: '/samples/new-drums/snare/snare_deebo_.wav' },
        { id: 'nd_snare_east_side_.wav', label: "Snare [ East Side ]", category: 'snare', url: '/samples/new-drums/snare/snare_east_side_.wav' },
        { id: 'nd_snare_hi_roller_.wav', label: "Snare [ Hi Roller ]", category: 'snare', url: '/samples/new-drums/snare/snare_hi_roller_.wav' },
        { id: 'nd_snare_mcflury_.wav', label: "Snare [ McFlury ]", category: 'snare', url: '/samples/new-drums/snare/snare_mcflury_.wav' },
        { id: 'nd__jynx_snares_-_rave.wav', label: "[JYNX] Snares - rave", category: 'snare', url: '/samples/new-drums/snare/_jynx_snares_-_rave.wav' },
        { id: 'nd_snare_30_roc_.wav', label: "Snare [ 30 Roc ]", category: 'snare', url: '/samples/new-drums/snare/snare_30_roc_.wav' },
        { id: 'nd_snare_filler_.wav', label: "Snare [ Filler ]", category: 'snare', url: '/samples/new-drums/snare/snare_filler_.wav' },
        { id: 'nd_snare_wrld_.wav', label: "Snare [ WRLD ]", category: 'snare', url: '/samples/new-drums/snare/snare_wrld_.wav' },
        { id: 'nd_snare_zay_.wav', label: "Snare [ Zay ]", category: 'snare', url: '/samples/new-drums/snare/snare_zay_.wav' },
        { id: 'nd__jynx_snares_-_atomic.wav', label: "[JYNX] Snares - atom", category: 'snare', url: '/samples/new-drums/snare/_jynx_snares_-_atomic.wav' },
],
    hihat: [
        { id: 'distkit-hatclsd.wav', label: 'DistKit Clsd', category: 'hihat', url: '/samples/distkit-hatclsd.wav' },
        { id: 'distkit-hatopen.wav', label: 'DistKit Open', category: 'hihat', url: '/samples/distkit-hatopen.wav' },
        { id: 'sdbkit-hatclsd.wav', label: 'SDBKit Clsd', category: 'hihat', url: '/samples/sdbkit-hatclsd.wav' },
        { id: 'sdbkit-hatopen.wav', label: 'SDBKit Open', category: 'hihat', url: '/samples/sdbkit-hatopen.wav' },
        { id: 'synthkit-hatclsd.wav', label: 'SynthKit Clsd', category: 'hihat', url: '/samples/synthkit-hatclsd.wav' },
        { id: 'synthkit-hatopen.wav', label: 'SynthKit Open', category: 'hihat', url: '/samples/synthkit-hatopen.wav' },
        { id: 'x0xproc1-hatclsd.wav', label: 'X0x1 Clsd', category: 'hihat', url: '/samples/x0xproc1-hatclsd.wav' },
        { id: 'x0xproc1-hatopen.wav', label: 'X0x1 Open', category: 'hihat', url: '/samples/x0xproc1-hatopen.wav' },
        { id: 'x0xproc2-hatclsd.wav', label: 'X0x2 Clsd', category: 'hihat', url: '/samples/x0xproc2-hatclsd.wav' },
        { id: 'x0xproc2-hatopen.wav', label: 'X0x2 Open', category: 'hihat', url: '/samples/x0xproc2-hatopen.wav' },
            { id: 'nd_closed_cymbol_retardant_.wav', label: "Closed Cymbol [ Reta", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_retardant_.wav' },
        { id: 'nd_closed_cymbol_ronny_j_.wav', label: "Closed Cymbol [ Ronn", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_ronny_j_.wav' },
        { id: 'nd_hi_hat_-_2_vaults.wav', label: "Hi Hat - 2 Vaults", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_2_vaults.wav' },
        { id: 'nd_hi_hat_-_66.wav', label: "Hi Hat - 66", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_66.wav' },
        { id: 'nd_hi_hat_-_dangerous.wav', label: "Hi Hat - Dangerous", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_dangerous.wav' },
        { id: 'nd_hi_hat_bent_.wav', label: "Hi Hat [ Bent ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_bent_.wav' },
        { id: 'nd_hi_hat_era_.wav', label: "Hi Hat [ Era ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_era_.wav' },
        { id: 'nd_hi_hat_i_fall_.wav', label: "Hi Hat [ I Fall ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_i_fall_.wav' },
        { id: 'nd_hi_hat_kd_.wav', label: "Hi Hat [ KD ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_kd_.wav' },
        { id: 'nd_hi_hat_marble_.wav', label: "Hi Hat [ Marble ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_marble_.wav' },
        { id: 'nd_hi_hat_range_.wav', label: "Hi Hat [ Range ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_range_.wav' },
        { id: 'nd_hi_hat_reala_.wav', label: "Hi Hat ” reala ”", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_reala_.wav' },
        { id: 'nd_live_hat_-_machine.wav', label: "Live Hat - Machine", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_machine.wav' },
        { id: 'nd__ardist_hi_hat_-_crutches.wav', label: "[ARDIST] Hi Hat - Cr", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hat_-_crutches.wav' },
        { id: 'nd__ardist_hi_hats_-_doomb.wav', label: "[ARDIST] Hi Hats - D", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hats_-_doomb.wav' },
        { id: 'nd__ardist_hi_hats_-_this_waveform_tho....wav', label: "[ARDIST] Hi Hats - t", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hats_-_this_waveform_tho....wav' },
        { id: 'nd_hi_hat_-_business.wav', label: "Hi Hat - Business", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_business.wav' },
        { id: 'nd_hi_hat_-_remember_me.wav', label: "Hi Hat - remember Me", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_remember_me.wav' },
        { id: 'nd_hi_hat_-_stacks.wav', label: "Hi Hat - Stacks", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_stacks.wav' },
        { id: 'nd_hi_hat_boom_.wav', label: "Hi Hat [ Boom ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_boom_.wav' },
        { id: 'nd_hi_hat_channel_6_.wav', label: "Hi Hat [ Channel 6 ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_channel_6_.wav' },
        { id: 'nd_hi_hat_chops_.wav', label: "Hi Hat [ Chops ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_chops_.wav' },
        { id: 'nd_hi_hat_gala_.wav', label: "Hi Hat [ Gala ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_gala_.wav' },
        { id: 'nd_hi_hat_ha_.wav', label: "Hi Hat [ Ha ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_ha_.wav' },
        { id: 'nd_hi_hat_ice_tray_.wav', label: "Hi Hat [ Ice Tray ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_ice_tray_.wav' },
        { id: 'nd_hi_hat_jet_stream_.wav', label: "Hi Hat [ Jet Stream ", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_jet_stream_.wav' },
        { id: 'nd_hi_hat_lookin_exoticc_.wav', label: "Hi Hat [ Lookin Exot", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_lookin_exoticc_.wav' },
        { id: 'nd_hi_hat_praise_.wav', label: "Hi Hat [ Praise ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_praise_.wav' },
        { id: 'nd_hi_hat_small_face_.wav', label: "Hi Hat [ Small Face ", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_small_face_.wav' },
        { id: 'nd_hi_hat_tick_.wav', label: "Hi Hat [ Tick ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_tick_.wav' },
        { id: 'nd_hi_hat_tsa_.wav', label: "Hi Hat [ TSA ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_tsa_.wav' },
        { id: 'nd_hi_hat_wah_wah_wah_.wav', label: "Hi Hat [ Wah Wah Wah", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_wah_wah_wah_.wav' },
        { id: 'nd_hi_hat_way_back_.wav', label: "Hi Hat [ Way Back ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_way_back_.wav' },
        { id: 'nd_hi_hat_zay_.wav', label: "Hi Hat [ Zay ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_zay_.wav' },
        { id: 'nd__ardist_hi_hat_-_8_to_9.wav', label: "[ARDIST] Hi Hat - 8 ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hat_-_8_to_9.wav' },
        { id: 'nd__ardist_hi_hat_-_crashing_it.wav', label: "[ARDIST] Hi Hat - cr", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hat_-_crashing_it.wav' },
        { id: 'nd__ardist_hi_hat_-_support.wav', label: "[ARDIST] Hi Hat - su", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hat_-_support.wav' },
        { id: 'nd__ardist_hi_hats_-_blem.wav', label: "[ARDIST] Hi Hats - B", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hats_-_blem.wav' },
        { id: 'nd__ardist_hi_hats_-_cracked.wav', label: "[ARDIST] Hi Hats - C", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hats_-_cracked.wav' },
        { id: 'nd__ardist_hi_hats_-_idk.wav', label: "[ARDIST] Hi Hats - i", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hats_-_idk.wav' },
        { id: 'nd__jynx_hi_hats_-_hit_it.wav', label: "[JYNX] Hi Hats - hit", category: 'hihat', url: '/samples/new-drums/hihat/_jynx_hi_hats_-_hit_it.wav' },
        { id: 'nd__jynx_hi_hats_-_off-white.wav', label: "[JYNX] Hi Hats - off", category: 'hihat', url: '/samples/new-drums/hihat/_jynx_hi_hats_-_off-white.wav' },
        { id: 'nd_hi_hat_-_4_vaults.wav', label: "Hi Hat - 4 Vaults", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_4_vaults.wav' },
        { id: 'nd_hi_hat_-_baby.wav', label: "Hi Hat - Baby", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_-_baby.wav' },
        { id: 'nd_hi_hat_famous_.wav', label: "Hi Hat [ Famous ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_famous_.wav' },
        { id: 'nd_hi_hat_gates_.wav', label: "Hi Hat [ Gates ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_gates_.wav' },
        { id: 'nd_hi_hat_hacked_instagram_.wav', label: "Hi hat [ Hacked Inst", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_hacked_instagram_.wav' },
        { id: 'nd_hi_hat_heat_.wav', label: "Hi Hat [ Heat ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_heat_.wav' },
        { id: 'nd_hi_hat_louder_.wav', label: "Hi Hat [ Louder ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_louder_.wav' },
        { id: 'nd_hi_hat_rage_.wav', label: "Hi Hat [ Rage ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_rage_.wav' },
        { id: 'nd_hi_hat_rat_.wav', label: "Hi Hat [ Rat ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_rat_.wav' },
        { id: 'nd_hi_hat_spill_.wav', label: "Hi Hat [ Spill ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_spill_.wav' },
        { id: 'nd_hi_hat_summer_.wav', label: "Hi Hat [ Summer ]", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_summer_.wav' },
        { id: 'nd__blvnts_hi_hat_-_balenciaga.wav', label: "[BLVNTS] Hi Hat - Ba", category: 'hihat', url: '/samples/new-drums/hihat/_blvnts_hi_hat_-_balenciaga.wav' },
        { id: 'nd__blvnts_hi_hat_-_bando.wav', label: "[BLVNTS] Hi Hat - Ba", category: 'hihat', url: '/samples/new-drums/hihat/_blvnts_hi_hat_-_bando.wav' },
        { id: 'nd__blvnts_hi_hat_-_drip.wav', label: "[BLVNTS] Hi Hat - Dr", category: 'hihat', url: '/samples/new-drums/hihat/_blvnts_hi_hat_-_drip.wav' },
        { id: 'nd__jynx_hi_hats_-_clutter.wav', label: "[JYNX] Hi Hats - clu", category: 'hihat', url: '/samples/new-drums/hihat/_jynx_hi_hats_-_clutter.wav' },
        { id: 'nd__jynx_hi_hats_-_crepe.wav', label: "[JYNX] Hi Hats - cre", category: 'hihat', url: '/samples/new-drums/hihat/_jynx_hi_hats_-_crepe.wav' },
        { id: 'nd_closed_cymbol_mai_.wav', label: "Closed Cymbol [ Mai ", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_mai_.wav' },
        { id: 'nd_closed_cymbol_pie_.wav', label: "Closed Cymbol [ Pie ", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_pie_.wav' },
        { id: 'nd_closed_cymbol_semi_.wav', label: "Closed Cymbol [ Semi", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_semi_.wav' },
        { id: 'nd_closed_cymbol_sleep_.wav', label: "Closed Cymbol [ Slee", category: 'hihat', url: '/samples/new-drums/hihat/closed_cymbol_sleep_.wav' },
        { id: 'nd_hi_hat_march_.wav', label: "Hi Hat ” march ”", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_march_.wav' },
        { id: 'nd_hi_hat_mini_travis_.wav', label: "Hi Hat ” mini travis", category: 'hihat', url: '/samples/new-drums/hihat/hi_hat_mini_travis_.wav' },
        { id: 'nd_live_hat_-_90210.wav', label: "Live Hat - 90210", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_90210.wav' },
        { id: 'nd_live_hat_-_annoying.wav', label: "Live Hat - Annoying", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_annoying.wav' },
        { id: 'nd_live_hat_-_antidote.wav', label: "Live Hat - Antidote", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_antidote.wav' },
        { id: 'nd_live_hat_-_blue_pill.wav', label: "Live Hat - Blue Pill", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_blue_pill.wav' },
        { id: 'nd_live_hat_-_drank.wav', label: "Live Hat - Drank", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_drank.wav' },
        { id: 'nd_live_hat_-_idk_why.wav', label: "Live Hat - idk why", category: 'hihat', url: '/samples/new-drums/hihat/live_hat_-_idk_why.wav' },
        { id: 'nd_open_hat_debt_.wav', label: "Open Hat [ Debt ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_debt_.wav' },
        { id: 'nd__ardist_hi_hat_-_aftermath.wav', label: "[ARDIST] Hi Hat - af", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_hi_hat_-_aftermath.wav' },
        { id: 'nd__ardist_open_hat_-_tresspass.wav', label: "[ARDIST] Open Hat - ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hat_-_tresspass.wav' },
        { id: 'nd_open_hat_next_.wav', label: "Open Hat [ , next ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_next_.wav' },
        { id: 'nd_open_hat_ban_.wav', label: "Open Hat [ Ban ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_ban_.wav' },
        { id: 'nd_open_hat_dollar_sign_.wav', label: "Open Hat [ Dollar Si", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_dollar_sign_.wav' },
        { id: 'nd_open_hat_dp_.wav', label: "Open Hat [ DP ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_dp_.wav' },
        { id: 'nd_open_hat_electricity_.wav', label: "Open Hat [ Electrici", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_electricity_.wav' },
        { id: 'nd_open_hat_my_people_.wav', label: "Open Hat [ My People", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_my_people_.wav' },
        { id: 'nd_open_hat_slap_hat_.wav', label: "Open Hat [ Slap Hat ", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_slap_hat_.wav' },
        { id: 'nd__ardist_open_hats_-_long_last.wav', label: "[ARDIST] Open Hats -", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hats_-_long_last.wav' },
        { id: 'nd__ardist_open_hats_-_snake.wav', label: "[ARDIST] Open Hats -", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hats_-_snake.wav' },
        { id: 'nd_open_hat_class_.wav', label: "Open Hat [ Class ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_class_.wav' },
        { id: 'nd_open_hat_coke_.wav', label: "Open Hat [ Coke ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_coke_.wav' },
        { id: 'nd_open_hat_heart_pump_.wav', label: "Open Hat [ Heart Pum", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_heart_pump_.wav' },
        { id: 'nd_open_hat_slat_.wav', label: "Open Hat [ Slat ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_slat_.wav' },
        { id: 'nd__ardist_open_hat_-_run_it.wav', label: "[ARDIST] Open Hat - ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hat_-_run_it.wav' },
        { id: 'nd_open_hat_-_bad_business.wav', label: "Open Hat - Bad Busin", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_-_bad_business.wav' },
        { id: 'nd_open_hat_eviction_.wav', label: "Open Hat [ Eviction ", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_eviction_.wav' },
        { id: 'nd_open_hat_lies_.wav', label: "Open Hat [ lies ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_lies_.wav' },
        { id: 'nd_open_hat_winner_.wav', label: "Open Hat [ Winner ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_winner_.wav' },
        { id: 'nd_open_hat_flappy_disc_.wav', label: "Open Hat [ Flappy Di", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_flappy_disc_.wav' },
        { id: 'nd_open_hat_ill_.wav', label: "Open Hat [ Ill ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_ill_.wav' },
        { id: 'nd_open_hat_isriel_.wav', label: "Open Hat [ Isriel ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_isriel_.wav' },
        { id: 'nd__ardist_open_hat_-_one_way.wav', label: "[ARDIST] Open Hat - ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hat_-_one_way.wav' },
        { id: 'nd_open_hat_24hrs_.wav', label: "Open Hat [ 24hrs ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_24hrs_.wav' },
        { id: 'nd_open_hat_88rising_.wav', label: "Open Hat [ 88Rising ", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_88rising_.wav' },
        { id: 'nd_open_hat_biebs_.wav', label: "Open Hat [ Biebs ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_biebs_.wav' },
        { id: 'nd_open_hat_bless_.wav', label: "Open Hat [ Bless ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_bless_.wav' },
        { id: 'nd_open_hat_crack_.wav', label: "Open Hat [ Crack ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_crack_.wav' },
        { id: 'nd_open_hat_insert_.wav', label: "Open Hat [ Insert ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_insert_.wav' },
        { id: 'nd_open_hat_more_.wav', label: "Open Hat [ More ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_more_.wav' },
        { id: 'nd_open_hat_szn_.wav', label: "Open Hat [ SZN ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_szn_.wav' },
        { id: 'nd_open_hat_the_creator_.wav', label: "Open Hat [ The Creat", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_the_creator_.wav' },
        { id: 'nd_open_hat_the_room_.wav', label: "Open Hat [ The Room ", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_the_room_.wav' },
        { id: 'nd_open_hat_trip_.wav', label: "Open Hat [ Trip ]", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_trip_.wav' },
        { id: 'nd__ardist_open_hats_-_cute.wav', label: "[ARDIST] Open Hats -", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hats_-_cute.wav' },
        { id: 'nd__ardist_open_hats_-_fa.wav', label: "[ARDIST] Open Hats -", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hats_-_fa.wav' },
        { id: 'nd__ardist_open_hats_-_teck.wav', label: "[ARDIST] Open Hats -", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hats_-_teck.wav' },
        { id: 'nd_open_hat_carefull_.wav', label: "Open Hat [ Carefull ", category: 'hihat', url: '/samples/new-drums/hihat/open_hat_carefull_.wav' },
        { id: 'nd__ardist_open_hat_-_oh_lord.wav', label: "[ARDIST] Open Hat - ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hat_-_oh_lord.wav' },
        { id: 'nd__ardist_open_hat_-_wavey.wav', label: "[ARDIST] Open Hat - ", category: 'hihat', url: '/samples/new-drums/hihat/_ardist_open_hat_-_wavey.wav' },
],
    perc: [
        { id: 'distkit-claves.wav', label: 'DistKit Claves', category: 'perc', url: '/samples/distkit-claves.wav' },
        { id: 'distkit-cowbell.wav', label: 'DistKit Cowbell', category: 'perc', url: '/samples/distkit-cowbell.wav' },
        { id: 'distkit-zap.wav', label: 'DistKit Zap', category: 'perc', url: '/samples/distkit-zap.wav' },
        { id: 'sdbkit-fmperc.wav', label: 'SDBKit FM', category: 'perc', url: '/samples/sdbkit-fmperc.wav' },
        { id: 'synthkit-8bit.wav', label: 'SynthKit 8-Bit', category: 'perc', url: '/samples/synthkit-8bit.wav' },
        { id: 'x0xproc1-rimshot.wav', label: 'X0x1 Rim', category: 'perc', url: '/samples/x0xproc1-rimshot.wav' },
        { id: 'x0xproc2-claves.wav', label: 'X0x2 Claves', category: 'perc', url: '/samples/x0xproc2-claves.wav' },
        { id: 'x0xproc2-cowbell.wav', label: 'X0x2 Cowbell', category: 'perc', url: '/samples/x0xproc2-cowbell.wav' },
        { id: 'x0xproc2-maracas.wav', label: 'X0x2 Maracas', category: 'perc', url: '/samples/x0xproc2-maracas.wav' },
        { id: 'x0xproc2-rimshot.wav', label: 'X0x2 Rim', category: 'perc', url: '/samples/x0xproc2-rimshot.wav' },
            { id: 'nd_fx_creepin_.wav', label: "FX [ Creepin_ ]", category: 'perc', url: '/samples/new-drums/perc/fx_creepin_.wav' },
        { id: 'nd_fx_effecc_.wav', label: "FX [ Effecc ]", category: 'perc', url: '/samples/new-drums/perc/fx_effecc_.wav' },
        { id: 'nd_fx_fight_me_mate_.wav', label: "FX ” fight me mate ”", category: 'perc', url: '/samples/new-drums/perc/fx_fight_me_mate_.wav' },
        { id: 'nd_fx_introducing_.wav', label: "FX ” introducing ”", category: 'perc', url: '/samples/new-drums/perc/fx_introducing_.wav' },
        { id: 'nd_fx_they_knew_.wav', label: "FX ” they knew ”", category: 'perc', url: '/samples/new-drums/perc/fx_they_knew_.wav' },
        { id: 'nd_drop_die_lit_.wav', label: "Drop [ Die Lit ]", category: 'perc', url: '/samples/new-drums/perc/drop_die_lit_.wav' },
        { id: 'nd_drop_happy_birthday_.wav', label: "Drop [ Happy Birthda", category: 'perc', url: '/samples/new-drums/perc/drop_happy_birthday_.wav' },
        { id: 'nd_drop_huncho_.wav', label: "Drop [ Huncho ]", category: 'perc', url: '/samples/new-drums/perc/drop_huncho_.wav' },
        { id: 'nd_drop_jedi_.wav', label: "Drop [ Jedi ]", category: 'perc', url: '/samples/new-drums/perc/drop_jedi_.wav' },
        { id: 'nd_drop_owch_.wav', label: "Drop [ Owch ]", category: 'perc', url: '/samples/new-drums/perc/drop_owch_.wav' },
        { id: 'nd_drop_ready_.wav', label: "Drop [ Ready ]", category: 'perc', url: '/samples/new-drums/perc/drop_ready_.wav' },
        { id: 'nd_drop_sad_.wav', label: "Drop [ SAD ]", category: 'perc', url: '/samples/new-drums/perc/drop_sad_.wav' },
        { id: 'nd_fx_say_sum_.wav', label: "FX [ Say Sum ]", category: 'perc', url: '/samples/new-drums/perc/fx_say_sum_.wav' },
        { id: 'nd_fx_tnt_.wav', label: "FX [ TNT ]", category: 'perc', url: '/samples/new-drums/perc/fx_tnt_.wav' },
        { id: 'nd_fx_killy_.wav', label: "FX ” killy ”", category: 'perc', url: '/samples/new-drums/perc/fx_killy_.wav' },
        { id: 'nd_fx_reginald_.wav', label: "FX ” Reginald ”", category: 'perc', url: '/samples/new-drums/perc/fx_reginald_.wav' },
        { id: 'nd_fx_wait_for_it..._drop_.wav', label: "FX ” wait for it... ", category: 'perc', url: '/samples/new-drums/perc/fx_wait_for_it..._drop_.wav' },
        { id: 'nd__ardist_fx_-_hate_red.wav', label: "[ARDIST] FX - Hate R", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_hate_red.wav' },
        { id: 'nd__ardist_fx_-_high.wav', label: "[ARDIST] FX - High", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_high.wav' },
        { id: 'nd__ardist_fx_-_sonic.wav', label: "[ARDIST] FX - Sonic", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_sonic.wav' },
        { id: 'nd_fx_alert_.wav', label: "FX [ Alert ]", category: 'perc', url: '/samples/new-drums/perc/fx_alert_.wav' },
        { id: 'nd_fx_anti_mortal_.wav', label: "FX [ Anti Mortal ]", category: 'perc', url: '/samples/new-drums/perc/fx_anti_mortal_.wav' },
        { id: 'nd_fx_facetime_.wav', label: "FX [ Facetime ]", category: 'perc', url: '/samples/new-drums/perc/fx_facetime_.wav' },
        { id: 'nd_fx_12_.wav', label: "FX ” 12 ”", category: 'perc', url: '/samples/new-drums/perc/fx_12_.wav' },
        { id: 'nd_fx_burr_.wav', label: "FX ” burr ”", category: 'perc', url: '/samples/new-drums/perc/fx_burr_.wav' },
        { id: 'nd_fx_drip_or_drown_114_bpm_.wav', label: "FX ” drip or drown ”", category: 'perc', url: '/samples/new-drums/perc/fx_drip_or_drown_114_bpm_.wav' },
        { id: 'nd_fx_incoming_.wav', label: "FX ” INCOMING ”", category: 'perc', url: '/samples/new-drums/perc/fx_incoming_.wav' },
        { id: 'nd_fx_spooky_highway_.wav', label: "FX ” spooky highway ", category: 'perc', url: '/samples/new-drums/perc/fx_spooky_highway_.wav' },
        { id: 'nd_fx_vroom_.wav', label: "FX ” VROOM ”", category: 'perc', url: '/samples/new-drums/perc/fx_vroom_.wav' },
        { id: 'nd__ardist_fx_-_2time.wav', label: "[ARDIST] FX - 2TIME", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_2time.wav' },
        { id: 'nd__ardist_fx_-_blip.wav', label: "[ARDIST] FX - BLIP", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_blip.wav' },
        { id: 'nd__ardist_fx_-_incoming_152_bpm_.wav', label: "[ARDIST] FX - Incomi", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_incoming_152_bpm_.wav' },
        { id: 'nd__ardist_fx_-_last_free_one.wav', label: "[ARDIST] FX - Last F", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_last_free_one.wav' },
        { id: 'nd__ardist_fx_-_nightmare_fuel.wav', label: "[ARDIST] FX - Nightm", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_nightmare_fuel.wav' },
        { id: 'nd__ardist_fx_-_petro.wav', label: "[ARDIST] FX - Petro", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_petro.wav' },
        { id: 'nd__blvnts_fx_-_detonate.wav', label: "[BLVNTS] FX - Detona", category: 'perc', url: '/samples/new-drums/perc/_blvnts_fx_-_detonate.wav' },
        { id: 'nd__blvnts_fx_-_laser.wav', label: "[BLVNTS] FX - Laser", category: 'perc', url: '/samples/new-drums/perc/_blvnts_fx_-_laser.wav' },
        { id: 'nd_fx_woah_i_made_this_.wav', label: "FX ” woah i made thi", category: 'perc', url: '/samples/new-drums/perc/fx_woah_i_made_this_.wav' },
        { id: 'nd_fye_asf_rise_drop.wav', label: "fye asf rise+drop", category: 'perc', url: '/samples/new-drums/perc/fye_asf_rise_drop.wav' },
        { id: 'nd_fx_portals_.wav', label: "FX [ Portals ]", category: 'perc', url: '/samples/new-drums/perc/fx_portals_.wav' },
        { id: 'nd_fx_big_on_big_.wav', label: "FX ” big on big ”", category: 'perc', url: '/samples/new-drums/perc/fx_big_on_big_.wav' },
        { id: 'nd_fx_country_roads_.wav', label: "FX ” country roads ”", category: 'perc', url: '/samples/new-drums/perc/fx_country_roads_.wav' },
        { id: 'nd_fx_fun_.wav', label: "FX ” fun ”", category: 'perc', url: '/samples/new-drums/perc/fx_fun_.wav' },
        { id: 'nd_fx_hard_.wav', label: "FX ” HARD ”", category: 'perc', url: '/samples/new-drums/perc/fx_hard_.wav' },
        { id: 'nd_fx_it_s_really_you_140_bpm_.wav', label: "FX ” it_s really you", category: 'perc', url: '/samples/new-drums/perc/fx_it_s_really_you_140_bpm_.wav' },
        { id: 'nd_fx_i_d_shorten_this_edit_2_.wav', label: "FX ” i_d shorten thi", category: 'perc', url: '/samples/new-drums/perc/fx_i_d_shorten_this_edit_2_.wav' },
        { id: 'nd_fx_i_d_shorten_this_edit_.wav', label: "FX ” i_d shorten thi", category: 'perc', url: '/samples/new-drums/perc/fx_i_d_shorten_this_edit_.wav' },
        { id: 'nd_fx_i_d_shorten_this_.wav', label: "FX ” i_d shorten thi", category: 'perc', url: '/samples/new-drums/perc/fx_i_d_shorten_this_.wav' },
        { id: 'nd_fx_last_call_edit_2_.wav', label: "FX ” last call EDIT ", category: 'perc', url: '/samples/new-drums/perc/fx_last_call_edit_2_.wav' },
        { id: 'nd_fx_last_call_edit_.wav', label: "FX ” last call EDIT ", category: 'perc', url: '/samples/new-drums/perc/fx_last_call_edit_.wav' },
        { id: 'nd_fx_last_call_.wav', label: "FX ” last call ”", category: 'perc', url: '/samples/new-drums/perc/fx_last_call_.wav' },
        { id: 'nd_fx_outcoming_.wav', label: "FX ” OUTCOMING ”", category: 'perc', url: '/samples/new-drums/perc/fx_outcoming_.wav' },
        { id: 'nd_fx_sign_up_.wav', label: "FX ” sign up ”", category: 'perc', url: '/samples/new-drums/perc/fx_sign_up_.wav' },
        { id: 'nd_fx_spotlight_.wav', label: "FX ” spotlight ”", category: 'perc', url: '/samples/new-drums/perc/fx_spotlight_.wav' },
        { id: 'nd_fx_this_better_drop_.wav', label: "FX ” this better dro", category: 'perc', url: '/samples/new-drums/perc/fx_this_better_drop_.wav' },
        { id: 'nd_fx_trap_or_trap_.wav', label: "FX ” trap or trap ”", category: 'perc', url: '/samples/new-drums/perc/fx_trap_or_trap_.wav' },
        { id: 'nd_fx_wtf..._.wav', label: "FX ” wtf... ”", category: 'perc', url: '/samples/new-drums/perc/fx_wtf..._.wav' },
        { id: 'nd_fyeeeeee_riser.wav', label: "fyeeeeee riser", category: 'perc', url: '/samples/new-drums/perc/fyeeeeee_riser.wav' },
        { id: 'nd_riser_fresh_air_.wav', label: "Riser [ Fresh Air ]", category: 'perc', url: '/samples/new-drums/perc/riser_fresh_air_.wav' },
        { id: 'nd__ardist_fx_-_plvt_144_bpm_.wav', label: "[ARDIST] FX - Plvt [", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_plvt_144_bpm_.wav' },
        { id: 'nd__jynx_fx_-_built_e_.wav', label: "[JYNX] FX - built [ ", category: 'perc', url: '/samples/new-drums/perc/_jynx_fx_-_built_e_.wav' },
        { id: 'nd__jynx_fx_-_halls.wav', label: "[JYNX] FX - halls", category: 'perc', url: '/samples/new-drums/perc/_jynx_fx_-_halls.wav' },
        { id: 'nd_fx_the_drop_.wav', label: "FX [ The Drop ]", category: 'perc', url: '/samples/new-drums/perc/fx_the_drop_.wav' },
        { id: 'nd_fx_big_racks_intro_.wav', label: "FX ” big racks intro", category: 'perc', url: '/samples/new-drums/perc/fx_big_racks_intro_.wav' },
        { id: 'nd_fx_mini_sweep_.wav', label: "FX ” Mini Sweep ”", category: 'perc', url: '/samples/new-drums/perc/fx_mini_sweep_.wav' },
        { id: 'nd_fx_rdy_edit_.wav', label: "FX ” rdy EDIT ”", category: 'perc', url: '/samples/new-drums/perc/fx_rdy_edit_.wav' },
        { id: 'nd_fx_rdy_.wav', label: "FX ” rdy ”", category: 'perc', url: '/samples/new-drums/perc/fx_rdy_.wav' },
        { id: 'nd_fx_rwhoosh_edit_.wav', label: "FX ” rwhoosh EDIT ”", category: 'perc', url: '/samples/new-drums/perc/fx_rwhoosh_edit_.wav' },
        { id: 'nd_fx_rwhoosh_.wav', label: "FX ” rwhoosh ”", category: 'perc', url: '/samples/new-drums/perc/fx_rwhoosh_.wav' },
        { id: 'nd_fx_tiny_.wav', label: "FX ” Tiny ”", category: 'perc', url: '/samples/new-drums/perc/fx_tiny_.wav' },
        { id: 'nd_fx_use_this_now_.wav', label: "FX ” use this now ”", category: 'perc', url: '/samples/new-drums/perc/fx_use_this_now_.wav' },
        { id: 'nd_fx_wait_for_it..._.wav', label: "FX ” wait for it... ", category: 'perc', url: '/samples/new-drums/perc/fx_wait_for_it..._.wav' },
        { id: 'nd_riser_stomp_sauce.wav', label: "riser+stomp = sauce", category: 'perc', url: '/samples/new-drums/perc/riser_stomp_sauce.wav' },
        { id: 'nd_stomp_big_bank_.wav', label: "Stomp [ Big Bank ]", category: 'perc', url: '/samples/new-drums/perc/stomp_big_bank_.wav' },
        { id: 'nd_stomp_bot_.wav', label: "Stomp [ Bot ]", category: 'perc', url: '/samples/new-drums/perc/stomp_bot_.wav' },
        { id: 'nd_stomp_jet_.wav', label: "Stomp [ Jet ]", category: 'perc', url: '/samples/new-drums/perc/stomp_jet_.wav' },
        { id: 'nd_stomp_shrink_.wav', label: "Stomp [ Shrink ]", category: 'perc', url: '/samples/new-drums/perc/stomp_shrink_.wav' },
        { id: 'nd_stomp_smoke_.wav', label: "Stomp [ Smoke ]", category: 'perc', url: '/samples/new-drums/perc/stomp_smoke_.wav' },
        { id: 'nd_beepbeepbeep.wav', label: "beepbeepbeep", category: 'perc', url: '/samples/new-drums/perc/beepbeepbeep.wav' },
        { id: 'nd_fx_atake_.wav', label: "FX [ Atake ]", category: 'perc', url: '/samples/new-drums/perc/fx_atake_.wav' },
        { id: 'nd__ardist_fx_-_emote_144_bpm_.wav', label: "[ARDIST] FX - Emote ", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_emote_144_bpm_.wav' },
        { id: 'nd__ardist_fx_-_reup_152_bpm_.wav', label: "[ARDIST] FX - Reup [", category: 'perc', url: '/samples/new-drums/perc/_ardist_fx_-_reup_152_bpm_.wav' },
        { id: 'nd_fx_insert_2_.wav', label: "FX [ Insert 2 ]", category: 'perc', url: '/samples/new-drums/perc/fx_insert_2_.wav' },
        { id: 'nd_fx_insert_.wav', label: "FX [ Insert ]", category: 'perc', url: '/samples/new-drums/perc/fx_insert_.wav' },
        { id: 'nd_cango_tech_.wav', label: "Cango [ Tech ]", category: 'perc', url: '/samples/new-drums/perc/cango_tech_.wav' },
        { id: 'nd_perc_-_packin.wav', label: "Perc - Packin", category: 'perc', url: '/samples/new-drums/perc/perc_-_packin.wav' },
        { id: 'nd_perc_-_pascal.wav', label: "Perc - Pascal", category: 'perc', url: '/samples/new-drums/perc/perc_-_pascal.wav' },
        { id: 'nd_perc_beni_.wav', label: "Perc [ Beni ]", category: 'perc', url: '/samples/new-drums/perc/perc_beni_.wav' },
        { id: 'nd_rim_insert_.wav', label: "Rim [ Insert ]", category: 'perc', url: '/samples/new-drums/perc/rim_insert_.wav' },
        { id: 'nd_tabla_ting_.wav', label: "Tabla [ Ting ]", category: 'perc', url: '/samples/new-drums/perc/tabla_ting_.wav' },
        { id: 'nd_tom_bans_.wav', label: "Tom [ Bans ]", category: 'perc', url: '/samples/new-drums/perc/tom_bans_.wav' },
        { id: 'nd_tom_pick_up_.wav', label: "Tom [ Pick Up ]", category: 'perc', url: '/samples/new-drums/perc/tom_pick_up_.wav' },
        { id: 'nd_cango_pick_up_.wav', label: "Cango [ Pick Up ]", category: 'perc', url: '/samples/new-drums/perc/cango_pick_up_.wav' },
        { id: 'nd_cango_zay_.wav', label: "Cango [ Zay ]", category: 'perc', url: '/samples/new-drums/perc/cango_zay_.wav' },
        { id: 'nd_perc_awge_.wav', label: "Perc [ AWGE ]", category: 'perc', url: '/samples/new-drums/perc/perc_awge_.wav' },
        { id: 'nd_perc_thugger_.wav', label: "Perc [ Thugger ]", category: 'perc', url: '/samples/new-drums/perc/perc_thugger_.wav' },
        { id: 'nd_perc_-_shotta.wav', label: "Perc - Shotta", category: 'perc', url: '/samples/new-drums/perc/perc_-_shotta.wav' },
        { id: 'nd_perc_3hree_shooter_.wav', label: "Perc [ 3hree Shooter", category: 'perc', url: '/samples/new-drums/perc/perc_3hree_shooter_.wav' },
        { id: 'nd_perc_a_ap_.wav', label: "Perc [ A$AP ]", category: 'perc', url: '/samples/new-drums/perc/perc_a_ap_.wav' },
        { id: 'nd_perc_pick_up_.wav', label: "Perc [ Pick Up ]", category: 'perc', url: '/samples/new-drums/perc/perc_pick_up_.wav' },
        { id: 'nd_perc_xo_tour_llif3_2_.wav', label: "Perc [ XO Tour Llif3", category: 'perc', url: '/samples/new-drums/perc/perc_xo_tour_llif3_2_.wav' },
        { id: 'nd_perc_xo_tour_llif3_.wav', label: "Perc [ XO Tour Llif3", category: 'perc', url: '/samples/new-drums/perc/perc_xo_tour_llif3_.wav' },
        { id: 'nd_perc_you_said_.wav', label: "Perc [ You Said ]", category: 'perc', url: '/samples/new-drums/perc/perc_you_said_.wav' },
        { id: 'nd__ardist_perc_-_sensor.wav', label: "[ARDIST] Perc - Sens", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_sensor.wav' },
        { id: 'nd__ardist_percs_-_float.wav', label: "[ARDIST] Percs - Flo", category: 'perc', url: '/samples/new-drums/perc/_ardist_percs_-_float.wav' },
        { id: 'nd__jynx_percs_-_race.wav', label: "[JYNX] Percs - race", category: 'perc', url: '/samples/new-drums/perc/_jynx_percs_-_race.wav' },
        { id: 'nd_perc_-_pills.wav', label: "Perc - Pills", category: 'perc', url: '/samples/new-drums/perc/perc_-_pills.wav' },
        { id: 'nd_perc_blocc_.wav', label: "Perc [ Blocc ]", category: 'perc', url: '/samples/new-drums/perc/perc_blocc_.wav' },
        { id: 'nd_perc_failure_.wav', label: "Perc [ Failure ]", category: 'perc', url: '/samples/new-drums/perc/perc_failure_.wav' },
        { id: 'nd_perc_fresh_air_.wav', label: "Perc [ Fresh Air ]", category: 'perc', url: '/samples/new-drums/perc/perc_fresh_air_.wav' },
        { id: 'nd_perc_h8_.wav', label: "Perc [ H8 ]", category: 'perc', url: '/samples/new-drums/perc/perc_h8_.wav' },
        { id: 'nd_perc_luv_.wav', label: "Perc [ Luv ]", category: 'perc', url: '/samples/new-drums/perc/perc_luv_.wav' },
        { id: 'nd_perc_ricch_.wav', label: "Perc [ Ricch ]", category: 'perc', url: '/samples/new-drums/perc/perc_ricch_.wav' },
        { id: 'nd_perc_shrink_.wav', label: "Perc [ Shrink ]", category: 'perc', url: '/samples/new-drums/perc/perc_shrink_.wav' },
        { id: 'nd_perc_snar_.wav', label: "Perc [ Snar ]", category: 'perc', url: '/samples/new-drums/perc/perc_snar_.wav' },
        { id: 'nd_perc_ultimate_.wav', label: "Perc [ Ultimate ]", category: 'perc', url: '/samples/new-drums/perc/perc_ultimate_.wav' },
        { id: 'nd__ardist_perc_-_ov.wav', label: "[ARDIST] Perc - OV", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_ov.wav' },
        { id: 'nd__ardist_percs_-_slatt.wav', label: "[ARDIST] Percs - sla", category: 'perc', url: '/samples/new-drums/perc/_ardist_percs_-_slatt.wav' },
        { id: 'nd__ardist_percs_-_xans_lean.wav', label: "[ARDIST] Percs - Xan", category: 'perc', url: '/samples/new-drums/perc/_ardist_percs_-_xans_lean.wav' },
        { id: 'nd__blvnts_perc_-_carti.wav', label: "[BLVNTS] Perc - Cart", category: 'perc', url: '/samples/new-drums/perc/_blvnts_perc_-_carti.wav' },
        { id: 'nd__jynx_percs_-_cannon.wav', label: "[JYNX] Percs - canno", category: 'perc', url: '/samples/new-drums/perc/_jynx_percs_-_cannon.wav' },
        { id: 'nd__jynx_percs_-_duubi.wav', label: "[JYNX] Percs - duubi", category: 'perc', url: '/samples/new-drums/perc/_jynx_percs_-_duubi.wav' },
        { id: 'nd_perc_-_army.wav', label: "Perc - Army", category: 'perc', url: '/samples/new-drums/perc/perc_-_army.wav' },
        { id: 'nd_perc_fishing_rod_.wav', label: "Perc [ Fishing Rod ]", category: 'perc', url: '/samples/new-drums/perc/perc_fishing_rod_.wav' },
        { id: 'nd_perc_bonk_.wav', label: "Perc [ Bonk ]", category: 'perc', url: '/samples/new-drums/perc/perc_bonk_.wav' },
        { id: 'nd_perc_cast_obsidion_.wav', label: "Perc [ Cast Obsidion", category: 'perc', url: '/samples/new-drums/perc/perc_cast_obsidion_.wav' },
        { id: 'nd_perc_drip_.wav', label: "Perc [ Drip ]", category: 'perc', url: '/samples/new-drums/perc/perc_drip_.wav' },
        { id: 'nd_perc_lil_one_.wav', label: "Perc [ Lil One ]", category: 'perc', url: '/samples/new-drums/perc/perc_lil_one_.wav' },
        { id: 'nd_perc_metro_.wav', label: "Perc [ Metro ]", category: 'perc', url: '/samples/new-drums/perc/perc_metro_.wav' },
        { id: 'nd_perc_pick_it_up_.wav', label: "Perc [ Pick It Up ]", category: 'perc', url: '/samples/new-drums/perc/perc_pick_it_up_.wav' },
        { id: 'nd__blvnts_perc_-_predator.wav', label: "[BLVNTS] Perc - Pred", category: 'perc', url: '/samples/new-drums/perc/_blvnts_perc_-_predator.wav' },
        { id: 'nd__jynx_percs_-_retrolog.wav', label: "[JYNX] Percs - retro", category: 'perc', url: '/samples/new-drums/perc/_jynx_percs_-_retrolog.wav' },
        { id: 'nd__jynx_percs_-_taboo.wav', label: "[JYNX] Percs - taboo", category: 'perc', url: '/samples/new-drums/perc/_jynx_percs_-_taboo.wav' },
        { id: 'nd_perc_rattle_shake_.wav', label: "Perc [ Rattle Shake ", category: 'perc', url: '/samples/new-drums/perc/perc_rattle_shake_.wav' },
        { id: 'nd_perc_sae_.wav', label: "Perc [ Sae ]", category: 'perc', url: '/samples/new-drums/perc/perc_sae_.wav' },
        { id: 'nd_perc_shack_.wav', label: "Perc [ Shack ]", category: 'perc', url: '/samples/new-drums/perc/perc_shack_.wav' },
        { id: 'nd_shake_loop_mud_180_bpm.wav', label: "Shake Loop [ Mud ] 1", category: 'perc', url: '/samples/new-drums/perc/shake_loop_mud_180_bpm.wav' },
        { id: 'nd_shake_beasty_.wav', label: "Shake [ Beasty ]", category: 'perc', url: '/samples/new-drums/perc/shake_beasty_.wav' },
        { id: 'nd_shake_don_t_sleep_.wav', label: "Shake [ Don_t Sleep ", category: 'perc', url: '/samples/new-drums/perc/shake_don_t_sleep_.wav' },
        { id: 'nd_shake_foli_.wav', label: "Shake [ Foli ]", category: 'perc', url: '/samples/new-drums/perc/shake_foli_.wav' },
        { id: 'nd_shake_ripped_.wav', label: "Shake [ Ripped ]", category: 'perc', url: '/samples/new-drums/perc/shake_ripped_.wav' },
        { id: 'nd_shaker_-_can_t_speak.wav', label: "Shaker - Can_t Speak", category: 'perc', url: '/samples/new-drums/perc/shaker_-_can_t_speak.wav' },
        { id: 'nd_tambourine_ronny_j_.wav', label: "Tambourine [ Ronny J", category: 'perc', url: '/samples/new-drums/perc/tambourine_ronny_j_.wav' },
        { id: 'nd__ardist_perc_-_forget_you.wav', label: "[ARDIST] Perc - Forg", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_forget_you.wav' },
        { id: 'nd__ardist_perc_-_i_know.wav', label: "[ARDIST] Perc - I Kn", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_i_know.wav' },
        { id: 'nd__blvnts_perc_-_drop.wav', label: "[BLVNTS] Perc - Drop", category: 'perc', url: '/samples/new-drums/perc/_blvnts_perc_-_drop.wav' },
        { id: 'nd_perc_sicko_.wav', label: "Perc [ Sicko ]", category: 'perc', url: '/samples/new-drums/perc/perc_sicko_.wav' },
        { id: 'nd_snare_-_spirit.wav', label: "Snare - Spirit", category: 'perc', url: '/samples/new-drums/perc/snare_-_spirit.wav' },
        { id: 'nd_snare_call_casting_.wav', label: "Snare [ Call Casting", category: 'perc', url: '/samples/new-drums/perc/snare_call_casting_.wav' },
        { id: 'nd_snare_in_my_feelings_.wav', label: "Snare [ In My Feelin", category: 'perc', url: '/samples/new-drums/perc/snare_in_my_feelings_.wav' },
        { id: 'nd_snare_jungle_rules_.wav', label: "Snare [ Jungle Rules", category: 'perc', url: '/samples/new-drums/perc/snare_jungle_rules_.wav' },
        { id: 'nd_snare_pariah_.wav', label: "Snare [ Pariah ]", category: 'perc', url: '/samples/new-drums/perc/snare_pariah_.wav' },
        { id: 'nd__ardist_perc_-_easy.wav', label: "[ARDIST] Perc - Easy", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_easy.wav' },
        { id: 'nd__ardist_perc_-_first_night.wav', label: "[ARDIST] Perc - Firs", category: 'perc', url: '/samples/new-drums/perc/_ardist_perc_-_first_night.wav' },
        { id: 'nd__ardist_percs_-_coke.wav', label: "[ARDIST] Percs - cok", category: 'perc', url: '/samples/new-drums/perc/_ardist_percs_-_coke.wav' },
        { id: 'nd__ardist_percs_-_shure.wav', label: "[ARDIST] Percs - Shu", category: 'perc', url: '/samples/new-drums/perc/_ardist_percs_-_shure.wav' },
        { id: 'nd__ardist_snares_-_ghost.wav', label: "[ARDIST] Snares - gh", category: 'perc', url: '/samples/new-drums/perc/_ardist_snares_-_ghost.wav' },
        { id: 'nd__ardist_snares_-_hella.wav', label: "[ARDIST] Snares - He", category: 'perc', url: '/samples/new-drums/perc/_ardist_snares_-_hella.wav' },
        { id: 'nd_perc_pick_up_the_phone_.wav', label: "Perc [ Pick Up The P", category: 'perc', url: '/samples/new-drums/perc/perc_pick_up_the_phone_.wav' },
        { id: 'nd_perc_stay_dangerous_.wav', label: "Perc [ Stay Dangerou", category: 'perc', url: '/samples/new-drums/perc/perc_stay_dangerous_.wav' },
        { id: 'nd_triangle_boss_.wav', label: "Triangle [ Boss ]", category: 'perc', url: '/samples/new-drums/perc/triangle_boss_.wav' },
        { id: 'nd_triangle_dated_.wav', label: "Triangle [ Dated ]", category: 'perc', url: '/samples/new-drums/perc/triangle_dated_.wav' },
        { id: 'nd_triangle_nami_.wav', label: "Triangle [ Nami ]", category: 'perc', url: '/samples/new-drums/perc/triangle_nami_.wav' },
        { id: 'nd_triangle_nami-tee_.wav', label: "Triangle [ Nami-tee ", category: 'perc', url: '/samples/new-drums/perc/triangle_nami-tee_.wav' },
        { id: 'nd_triangle_rent_money_.wav', label: "Triangle [ Rent Mone", category: 'perc', url: '/samples/new-drums/perc/triangle_rent_money_.wav' },
        { id: 'nd_triangle_scrape_.wav', label: "Triangle [ Scrape ]", category: 'perc', url: '/samples/new-drums/perc/triangle_scrape_.wav' },
        { id: 'nd_triangle_xtcy_.wav', label: "Triangle [ XTCY ]", category: 'perc', url: '/samples/new-drums/perc/triangle_xtcy_.wav' },
        { id: 'nd_vox_big_zay_.wav', label: "Vox [ Big Zay ]", category: 'perc', url: '/samples/new-drums/perc/vox_big_zay_.wav' },
        { id: 'nd_vox_cheer_.wav', label: "Vox [ Cheer ]", category: 'perc', url: '/samples/new-drums/perc/vox_cheer_.wav' },
        { id: 'nd_vox_digital_.wav', label: "Vox [ Digital ]", category: 'perc', url: '/samples/new-drums/perc/vox_digital_.wav' },
        { id: 'nd_vox_slime_.wav', label: "Vox [ Slime ]", category: 'perc', url: '/samples/new-drums/perc/vox_slime_.wav' },
        { id: 'nd_vox_zay_chant_.wav', label: "Vox [ Zay Chant ]", category: 'perc', url: '/samples/new-drums/perc/vox_zay_chant_.wav' },
        { id: 'nd_vox_bet_.wav', label: "Vox ” bet ”", category: 'perc', url: '/samples/new-drums/perc/vox_bet_.wav' },
        { id: 'nd_vox_green_and_purple_.wav', label: "Vox ” green and purp", category: 'perc', url: '/samples/new-drums/perc/vox_green_and_purple_.wav' },
        { id: 'nd_vox_purple_and_green_.wav', label: "Vox ” purple and gre", category: 'perc', url: '/samples/new-drums/perc/vox_purple_and_green_.wav' },
        { id: 'nd__ardist_vox_-_feelings.wav', label: "[ARDIST] Vox - Feeli", category: 'perc', url: '/samples/new-drums/perc/_ardist_vox_-_feelings.wav' },
        { id: 'nd__ardist_vox_-_holms.wav', label: "[ARDIST] Vox - Holms", category: 'perc', url: '/samples/new-drums/perc/_ardist_vox_-_holms.wav' },
        { id: 'nd__ardist_vox_-_impossible.wav', label: "[ARDIST] Vox - Impos", category: 'perc', url: '/samples/new-drums/perc/_ardist_vox_-_impossible.wav' },
        { id: 'nd_vox_canadian_goose_moan_.wav', label: "Vox [ Canadian Goose", category: 'perc', url: '/samples/new-drums/perc/vox_canadian_goose_moan_.wav' },
        { id: 'nd_vox_out_here_.wav', label: "Vox [ Out Here ]", category: 'perc', url: '/samples/new-drums/perc/vox_out_here_.wav' },
        { id: 'nd_vox_rawr_.wav', label: "Vox [ Rawr ]", category: 'perc', url: '/samples/new-drums/perc/vox_rawr_.wav' },
        { id: 'nd_vox_uuuh_.wav', label: "Vox [ Uuuh ]", category: 'perc', url: '/samples/new-drums/perc/vox_uuuh_.wav' },
        { id: 'nd_vox_yeahhh_.wav', label: "Vox [ Yeahhh ]", category: 'perc', url: '/samples/new-drums/perc/vox_yeahhh_.wav' },
        { id: 'nd_vox_top_off_.wav', label: "Vox ” top off ”", category: 'perc', url: '/samples/new-drums/perc/vox_top_off_.wav' },
        { id: 'nd__ardist_vox_-_ghast.wav', label: "[ARDIST] Vox - Ghast", category: 'perc', url: '/samples/new-drums/perc/_ardist_vox_-_ghast.wav' },
        { id: 'nd__ardist_vox_-_program.wav', label: "[ARDIST] Vox - Progr", category: 'perc', url: '/samples/new-drums/perc/_ardist_vox_-_program.wav' },
        { id: 'nd__jynx_vox_-_o-o.wav', label: "[JYNX] Vox - o-o", category: 'perc', url: '/samples/new-drums/perc/_jynx_vox_-_o-o.wav' },
],
    clap: [
        { id: 'distkit-clap.wav', label: 'DistKit', category: 'clap', url: '/samples/distkit-clap.wav' },
        { id: 'sdbkit-clap.wav', label: 'SDBKit', category: 'clap', url: '/samples/sdbkit-clap.wav' },
        { id: 'synthkit-clap.wav', label: 'SynthKit', category: 'clap', url: '/samples/synthkit-clap.wav' },
        { id: 'x0xproc1-clap.wav', label: 'X0x1', category: 'clap', url: '/samples/x0xproc1-clap.wav' },
        { id: 'x0xproc2-clap.wav', label: 'X0x2', category: 'clap', url: '/samples/x0xproc2-clap.wav' },
            { id: 'nd_clap_-_astronaut.wav', label: "Clap - Astronaut", category: 'clap', url: '/samples/new-drums/clap/clap_-_astronaut.wav' },
        { id: 'nd_clap_blap_.wav', label: "Clap [ Blap ]", category: 'clap', url: '/samples/new-drums/clap/clap_blap_.wav' },
        { id: 'nd_clap_crush_.wav', label: "Clap [ Crush ]", category: 'clap', url: '/samples/new-drums/clap/clap_crush_.wav' },
        { id: 'nd_clap_day_n_.wav', label: "Clap [ Day n_ ]", category: 'clap', url: '/samples/new-drums/clap/clap_day_n_.wav' },
        { id: 'nd_clap_g_wagon_.wav', label: "Clap [ G Wagon ]", category: 'clap', url: '/samples/new-drums/clap/clap_g_wagon_.wav' },
        { id: 'nd_clap_japan_.wav', label: "Clap [ Japan ]", category: 'clap', url: '/samples/new-drums/clap/clap_japan_.wav' },
        { id: 'nd_clap_luv_.wav', label: "Clap [ Luv ]", category: 'clap', url: '/samples/new-drums/clap/clap_luv_.wav' },
        { id: 'nd_clap_march_madness_.wav', label: "Clap [ March Madness", category: 'clap', url: '/samples/new-drums/clap/clap_march_madness_.wav' },
        { id: 'nd_clap_nite_.wav', label: "Clap [ Nite ]", category: 'clap', url: '/samples/new-drums/clap/clap_nite_.wav' },
        { id: 'nd_clap_no_keys_.wav', label: "Clap [ No Keys ]", category: 'clap', url: '/samples/new-drums/clap/clap_no_keys_.wav' },
        { id: 'nd_clap_no_shopping_.wav', label: "Clap [ No Shopping ]", category: 'clap', url: '/samples/new-drums/clap/clap_no_shopping_.wav' },
        { id: 'nd_clap_shack_clap_.wav', label: "Clap [ Shack Clap ]", category: 'clap', url: '/samples/new-drums/clap/clap_shack_clap_.wav' },
        { id: 'nd__ardist_clap_-_down_below.wav', label: "[ARDIST] Clap - Down", category: 'clap', url: '/samples/new-drums/clap/_ardist_clap_-_down_below.wav' },
        { id: 'nd__ardist_claps_-_ethnicc.wav', label: "[ARDIST] Claps - Eth", category: 'clap', url: '/samples/new-drums/clap/_ardist_claps_-_ethnicc.wav' },
        { id: 'nd__blvnts_clap_-_weight.wav', label: "[BLVNTS] Clap - Weig", category: 'clap', url: '/samples/new-drums/clap/_blvnts_clap_-_weight.wav' },
        { id: 'nd__jynx_claps_-_green_card.wav', label: "[JYNX] Claps - green", category: 'clap', url: '/samples/new-drums/clap/_jynx_claps_-_green_card.wav' },
        { id: 'nd__jynx_claps_-_kvass.wav', label: "[JYNX] Claps - kvass", category: 'clap', url: '/samples/new-drums/clap/_jynx_claps_-_kvass.wav' },
        { id: 'nd__jynx_claps_-_mop.wav', label: "[JYNX] Claps - mop", category: 'clap', url: '/samples/new-drums/clap/_jynx_claps_-_mop.wav' },
        { id: 'nd__jynx_claps_-_paint.wav', label: "[JYNX] Claps - paint", category: 'clap', url: '/samples/new-drums/clap/_jynx_claps_-_paint.wav' },
        { id: 'nd_clap_-_armed.wav', label: "Clap - Armed", category: 'clap', url: '/samples/new-drums/clap/clap_-_armed.wav' },
        { id: 'nd_clap_atl_.wav', label: "Clap [ ATL ]", category: 'clap', url: '/samples/new-drums/clap/clap_atl_.wav' },
        { id: 'nd_clap_barter_.wav', label: "Clap [ Barter ]", category: 'clap', url: '/samples/new-drums/clap/clap_barter_.wav' },
        { id: 'nd_clap_check_.wav', label: "Clap [ Check ]", category: 'clap', url: '/samples/new-drums/clap/clap_check_.wav' },
        { id: 'nd_clap_dates_.wav', label: "Clap [ Dates ]", category: 'clap', url: '/samples/new-drums/clap/clap_dates_.wav' },
        { id: 'nd_clap_late_nite_.wav', label: "Clap [ Late Nite ]", category: 'clap', url: '/samples/new-drums/clap/clap_late_nite_.wav' },
        { id: 'nd_clap_luger_slap_.wav', label: "Clap [ Luger Slap ]", category: 'clap', url: '/samples/new-drums/clap/clap_luger_slap_.wav' },
        { id: 'nd_clap_paint_.wav', label: "Clap [ Paint ]", category: 'clap', url: '/samples/new-drums/clap/clap_paint_.wav' },
        { id: 'nd_clap_pick_up_.wav', label: "Clap [ Pick Up ]", category: 'clap', url: '/samples/new-drums/clap/clap_pick_up_.wav' },
        { id: 'nd_clap_piea_.wav', label: "Clap [ Piea ]", category: 'clap', url: '/samples/new-drums/clap/clap_piea_.wav' },
        { id: 'nd_clap_pi_erre_slap_.wav', label: "Clap [ Pi_erre Slap ", category: 'clap', url: '/samples/new-drums/clap/clap_pi_erre_slap_.wav' },
        { id: 'nd_clap_thug_.wav', label: "Clap [ Thug ]", category: 'clap', url: '/samples/new-drums/clap/clap_thug_.wav' },
        { id: 'nd_clap_triple_time_.wav', label: "Clap [ Triple Time ]", category: 'clap', url: '/samples/new-drums/clap/clap_triple_time_.wav' },
        { id: 'nd_clap_wrld_.wav', label: "Clap [ WRLD ]", category: 'clap', url: '/samples/new-drums/clap/clap_wrld_.wav' },
        { id: 'nd_clap_yello_.wav', label: "Clap [ Yello ]", category: 'clap', url: '/samples/new-drums/clap/clap_yello_.wav' },
        { id: 'nd_clap_zay_.wav', label: "Clap [ Zay ]", category: 'clap', url: '/samples/new-drums/clap/clap_zay_.wav' },
        { id: 'nd__ardist_clap_-_act.wav', label: "[ARDIST] Clap - Act", category: 'clap', url: '/samples/new-drums/clap/_ardist_clap_-_act.wav' },
        { id: 'nd__ardist_clap_-_control.wav', label: "[ARDIST] Clap - Cont", category: 'clap', url: '/samples/new-drums/clap/_ardist_clap_-_control.wav' },
        { id: 'nd__ardist_clap_-_i_told_you.wav', label: "[ARDIST] Clap - I To", category: 'clap', url: '/samples/new-drums/clap/_ardist_clap_-_i_told_you.wav' },
        { id: 'nd__ardist_clap_-_no_remorse.wav', label: "[ARDIST] Clap - No R", category: 'clap', url: '/samples/new-drums/clap/_ardist_clap_-_no_remorse.wav' },
        { id: 'nd__ardist_claps_-_boat.wav', label: "[ARDIST] Claps - Boa", category: 'clap', url: '/samples/new-drums/clap/_ardist_claps_-_boat.wav' },
        { id: 'nd__ardist_claps_-_consume.wav', label: "[ARDIST] Claps - Con", category: 'clap', url: '/samples/new-drums/clap/_ardist_claps_-_consume.wav' },
        { id: 'nd__ardist_claps_-_kode.wav', label: "[ARDIST] Claps - Kod", category: 'clap', url: '/samples/new-drums/clap/_ardist_claps_-_kode.wav' },
        { id: 'nd__ardist_claps_-_pvl.wav', label: "[ARDIST] Claps - Pvl", category: 'clap', url: '/samples/new-drums/clap/_ardist_claps_-_pvl.wav' },
        { id: 'nd__jynx_claps_-_vac_seal.wav', label: "[JYNX] Claps - vac s", category: 'clap', url: '/samples/new-drums/clap/_jynx_claps_-_vac_seal.wav' },
        { id: 'nd_snap_champ_.wav', label: "Snap [ Champ ]", category: 'clap', url: '/samples/new-drums/clap/snap_champ_.wav' },
        { id: 'nd_snap_complex_.wav', label: "Snap [ Complex ]", category: 'clap', url: '/samples/new-drums/clap/snap_complex_.wav' },
        { id: 'nd_snap_infinity_.wav', label: "Snap [ Infinity ]", category: 'clap', url: '/samples/new-drums/clap/snap_infinity_.wav' },
        { id: 'nd_snap_koolade_.wav', label: "Snap [ Koolade ]", category: 'clap', url: '/samples/new-drums/clap/snap_koolade_.wav' },
        { id: 'nd_snap_lo_.wav', label: "Snap [ Lo ]", category: 'clap', url: '/samples/new-drums/clap/snap_lo_.wav' },
        { id: 'nd_snap_uncle_.wav', label: "Snap [ Uncle ]", category: 'clap', url: '/samples/new-drums/clap/snap_uncle_.wav' },
],
    cymbal: [
        { id: 'distkit-crash.wav', label: 'DistKit Crash', category: 'cymbal', url: '/samples/distkit-crash.wav' },
        { id: 'distkit-ride.wav', label: 'DistKit Ride', category: 'cymbal', url: '/samples/distkit-ride.wav' },
        { id: 'synthkit-crash.wav', label: 'SynthKit Crash', category: 'cymbal', url: '/samples/synthkit-crash.wav' },
        { id: 'synthkit-ride.wav', label: 'SynthKit Ride', category: 'cymbal', url: '/samples/synthkit-ride.wav' },
        { id: 'x0xproc1-crash.wav', label: 'X0x1 Crash', category: 'cymbal', url: '/samples/x0xproc1-crash.wav' },
        { id: 'x0xproc1-ride.wav', label: 'X0x1 Ride', category: 'cymbal', url: '/samples/x0xproc1-ride.wav' },
        { id: 'x0xproc2-cymbal.wav', label: 'X0x2 Cymbal', category: 'cymbal', url: '/samples/x0xproc2-cymbal.wav' },
            { id: 'nd_crash_beastie_.wav', label: "Crash [ Beastie ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_beastie_.wav' },
        { id: 'nd_crash_burr_.wav', label: "Crash [ Burr ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_burr_.wav' },
        { id: 'nd_crash_chopstar_.wav', label: "Crash [ Chopstar ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_chopstar_.wav' },
        { id: 'nd_crash_low_life_.wav', label: "Crash [ Low Life ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_low_life_.wav' },
        { id: 'nd_crash_oooooh_.wav', label: "Crash [ Oooooh ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_oooooh_.wav' },
        { id: 'nd_crash_shift_.wav', label: "Crash [ Shift ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_shift_.wav' },
        { id: 'nd_crash_who_dat_.wav', label: "Crash [ Who Dat ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_who_dat_.wav' },
        { id: 'nd_crash_magic_8_.wav', label: "Crash[ Magic 8 ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_magic_8_.wav' },
        { id: 'nd_crash_attack_.wav', label: "Crash [ Attack ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_attack_.wav' },
        { id: 'nd_crash_foe_.wav', label: "Crash [ Foe ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_foe_.wav' },
        { id: 'nd_crash_steam_.wav', label: "Crash [ Steam ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_steam_.wav' },
        { id: 'nd_crash_xanny_.wav', label: "Crash [ Xanny ]", category: 'cymbal', url: '/samples/new-drums/cymbal/crash_xanny_.wav' },
        { id: 'nd__ardist_crash_-_b.wav', label: "[ARDIST] Crash - B", category: 'cymbal', url: '/samples/new-drums/cymbal/_ardist_crash_-_b.wav' },
        { id: 'nd__ardist_crash_-_scare.wav', label: "[ARDIST] Crash - Sca", category: 'cymbal', url: '/samples/new-drums/cymbal/_ardist_crash_-_scare.wav' },
        { id: 'nd__ardist_crashes_-_drip.wav', label: "[ARDIST] Crashes - D", category: 'cymbal', url: '/samples/new-drums/cymbal/_ardist_crashes_-_drip.wav' },
        { id: 'nd__ardist_crashes_-_run_it_up.wav', label: "[ARDIST] Crashes - R", category: 'cymbal', url: '/samples/new-drums/cymbal/_ardist_crashes_-_run_it_up.wav' },
        { id: 'nd__jynx_crashes_-_clean_money.wav', label: "[JYNX] Crashes - cle", category: 'cymbal', url: '/samples/new-drums/cymbal/_jynx_crashes_-_clean_money.wav' },
        { id: 'nd__jynx_crashes_-_dirty_bands.wav', label: "[JYNX] Crashes - dir", category: 'cymbal', url: '/samples/new-drums/cymbal/_jynx_crashes_-_dirty_bands.wav' },
],
    tom: [
        { id: 'distkit-hitom.wav', label: 'DistKit High', category: 'tom', url: '/samples/distkit-hitom.wav' },
        { id: 'distkit-midtom.wav', label: 'DistKit Mid', category: 'tom', url: '/samples/distkit-midtom.wav' },
        { id: 'distkit-lotom.wav', label: 'DistKit Low', category: 'tom', url: '/samples/distkit-lotom.wav' },
        { id: 'sdbkit-hitom.wav', label: 'SDBKit High', category: 'tom', url: '/samples/sdbkit-hitom.wav' },
        { id: 'sdbkit-midtom.wav', label: 'SDBKit Mid', category: 'tom', url: '/samples/sdbkit-midtom.wav' },
        { id: 'sdbkit-lotom.wav', label: 'SDBKit Low', category: 'tom', url: '/samples/sdbkit-lotom.wav' },
        { id: 'synthkit-hitom.wav', label: 'SynthKit High', category: 'tom', url: '/samples/synthkit-hitom.wav' },
        { id: 'synthkit-midtom.wav', label: 'SynthKit Mid', category: 'tom', url: '/samples/synthkit-midtom.wav' },
        { id: 'synthkit-lotom.wav', label: 'SynthKit Low', category: 'tom', url: '/samples/synthkit-lotom.wav' },
        { id: 'x0xproc1-hitom.wav', label: 'X0x1 High', category: 'tom', url: '/samples/x0xproc1-hitom.wav' },
        { id: 'x0xproc1-midtom.wav', label: 'X0x1 Mid', category: 'tom', url: '/samples/x0xproc1-midtom.wav' },
        { id: 'x0xproc1-lotom.wav', label: 'X0x1 Low', category: 'tom', url: '/samples/x0xproc1-lotom.wav' },
        { id: 'x0xproc2-hitom.wav', label: 'X0x2 High', category: 'tom', url: '/samples/x0xproc2-hitom.wav' },
        { id: 'x0xproc2-midtom.wav', label: 'X0x2 Mid', category: 'tom', url: '/samples/x0xproc2-midtom.wav' },
        { id: 'x0xproc2-lotom.wav', label: 'X0x2 Low', category: 'tom', url: '/samples/x0xproc2-lotom.wav' },
    ]
};

// Helper to get a flat list of all samples
export const ALL_SAMPLES = Object.values(DRUM_SAMPLES).flat();
